-- SYNTHETIC DATA ONLY. Use a new empty demo project after the schema files.
begin;
insert into spending_categories (id,name,grp,kind) values
('salary','Salary','Income','income'),
('other-income','Other income','Income','income'),
('refunds','Refunds','Income','income'),
('from-people','Money from people (Tikkie)','Income','income'),
('own-transfers','Between own accounts','Transfers','transfer'),
('saving-investing','Saving and investing','Transfers','transfer'),
('loan-repayment','Loan repayments','Transfers','transfer'),
('rent','Rent and mortgage','Housing','expense'),
('utilities','Energy and water','Housing','expense'),
('internet-phone','Internet and phone','Housing','expense'),
('groceries','Groceries','Food and drink','expense'),
('restaurants','Restaurants and cafes','Food and drink','expense'),
('takeaway','Takeaway and delivery','Food and drink','expense'),
('public-transport','Public transport','Transport','expense'),
('car-fuel','Fuel, parking and car','Transport','expense'),
('taxi','Taxi and shared rides','Transport','expense'),
('clothing','Clothing and shoes','Shopping','expense'),
('electronics','Electronics','Shopping','expense'),
('home','Home and garden','Shopping','expense'),
('online-shopping','Online shopping','Shopping','expense'),
('personal-care','Drugstore and personal care','Health and care','expense'),
('health','Health and medical','Health and care','expense'),
('going-out','Going out and events','Leisure','expense'),
('sports','Sports and fitness','Leisure','expense'),
('travel','Travel and holidays','Leisure','expense'),
('subscriptions','Subscriptions','Leisure','expense'),
('insurance','Insurance','Fixed costs','expense'),
('taxes','Taxes and government','Fixed costs','expense'),
('education','Education and books','Fixed costs','expense'),
('bank-fees','Bank fees','Fixed costs','expense'),
('people','Payments to people (Tikkie)','Other','expense'),
('gifts','Gifts and donations','Other','expense'),
('cash','Cash withdrawals','Other','expense'),
('other','Other','Other','expense')
on conflict do nothing;
commit;
