'use strict';
/* Investment workspace. Calculations arrive from backend services; charts only render them. */
const INT={tab:store.get('int.tab','overview'),symbol:store.get('int.symbol',''),data:null,status:null,generation:0,account:'',cls:'all',sort:'score',filter:'',manager:'',quarter:'',genuine:true};
const INT_TABS=[['overview','Overview'],['portfolio','Portfolio Analysis'],['opportunities','Opportunities'],['investors','Superinvestors'],['insiders','Insiders'],['watchlist','Watchlist'],['research','Research']];
const intTables=new Map();
const intNum=(v,n=1)=>v==null?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:n});
const intPct=(v,n=1)=>v==null?'—':intNum(v,n)+'%';
const intRatio=(v,n=1)=>v==null?'—':intNum(v,n)+'×';
const intDate=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Unavailable';
const intEmpty=text=>`<div class="empty">${esc(text)}</div>`;
const intCard=(title,body,note='')=>`<section class="card"><div class="card-head"><h2>${esc(title)}</h2></div>${body}${note?`<p class="sub int-note">${esc(note)}</p>`:''}</section>`;
const intMetric=(label,value,note='')=>`<div class="int-metric"><span class="label">${esc(label)}</span><b>${value}</b>${note?`<span class="muted small">${esc(note)}</span>`:''}</div>`;
const intLink=s=>`<button class="linkish" type="button" data-int-company="${esc(s)}">${esc(s)}</button>`;
const intScore=sc=>sc?.overall==null?'<span class="muted" title="Insufficient component data">—</span>':`<span class="int-score" title="Rules v1 screening score; ${intPct(sc.coverage_pct)} data coverage">${intNum(sc.overall,0)}<small>/100</small></span>`;
function intURL(url,label){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return esc(label);}catch{return esc(label);}return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;}
async function intGet(name,q={}) {return cachedJSON('/api/intelligence/'+name+'?'+new URLSearchParams(q),{ttl:name==='status'?4000:300000});}
function intNavigate(tab,s){INT.tab=tab;store.set('int.tab',tab);if(s){INT.symbol=s;store.set('int.symbol',s);}if(view!=='holdings')location.hash='holdings';else holdings();}
function intNav(){return `<div class="int-nav" role="navigation" aria-label="Investment intelligence">${INT_TABS.map(([k,l])=>`<button type="button" data-int-tab="${k}" class="${INT.tab===k?'active':''}" aria-current="${INT.tab===k?'page':'false'}">${l}</button>`).join('')}<button type="button" class="int-alerts ${INT.tab==='alerts'?'active':''}" data-int-tab="alerts">Signals${S?.intelligence?.unread?` <span class="tag">${S.intelligence.unread}</span>`:''}</button></div>`;}
function intBind(root=$('#view')){
  $$('[data-int-sort]',root).forEach(b=>b.onclick=()=>{
    const table=b.closest('table'),spec=intTables.get(table?.id);if(!spec)return;
    const key=b.dataset.intSort,desc=table.dataset.sort===key?table.dataset.desc!=='true':true;
    table.dataset.sort=key;table.dataset.desc=String(desc);
    const sorted=[...spec.rows].sort((a,b)=>{if(a[key]==null)return b[key]==null?0:1;if(b[key]==null)return -1;
      const av=Array.isArray(a[key])?a[key].length:a[key],bv=Array.isArray(b[key])?b[key].length:b[key];
      return (typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv)))*(desc?-1:1);});
    table.querySelector('tbody').innerHTML=sorted.map(spec.render).join('');intBind(table);
  });
  $$('[data-int-tab]',root).forEach(b=>b.onclick=()=>intNavigate(b.dataset.intTab));
  $$('[data-int-company]',root).forEach(b=>b.onclick=()=>intNavigate('research',b.dataset.intCompany));
  $$('[data-int-chat]',root).forEach(b=>b.onclick=()=>{const question=b.dataset.intChat;openChat({text:question,ctx:{title:INT.symbol?INT.symbol+' research':'Investment intelligence',text:'Use the local investment tools for all calculations. Show source dates and coverage; research opinions separately from reported facts.'},conv:'intelligence-'+(INT.symbol||'portfolio')});});
  $$('[data-int-refresh]',root).forEach(b=>b.onclick=async()=>{b.disabled=true;try{await post('/api/intelligence/refresh',b.dataset.intRefresh?{symbol:b.dataset.intRefresh}:{});toast('Updating investment data');intPoll();}catch(e){toast(e.message);}finally{b.disabled=false;}});
}
const originalHoldings=holdings;
holdings=function(){
  if(INT.tab==='overview'){
    originalHoldings();$('#view').insertAdjacentHTML('afterbegin',intNav());
    const hero=$('.inv-hero');if(hero)hero.insertAdjacentHTML('afterend','<div id="intOverviewSignals"></div>');
    intBind();intOverview();return;
  }
  intWorkspace();
};
async function intOverview(){
  const slot=$('#intOverviewSignals');if(!slot)return;
  const signals=S.intelligence?.signals||[];
  slot.innerHTML=signals.length?intCard('Investment signals',signals.slice(0,2).map(s=>`<div class="list-row"><div><b>${esc(s.title)}</b><div class="muted small">${esc(s.symbol)} · ${esc(s.detail)}</div></div><button type="button" class="linkish small" data-int-tab="alerts">Review</button></div>`).join('')):'';
  intBind(slot);
}
let intPollTimer;
function intPoll(){clearTimeout(intPollTimer);intPollTimer=setTimeout(async()=>{try{INT.status=await intGet('status');const running=INT.status.jobs.some(j=>j.status==='running');if(['holdings','explore'].includes(view) && INT.tab!=='overview'){const el=$('#intFresh');if(el)el.textContent=intFreshText(INT.status);}if(running)intPoll();else if(['holdings','explore'].includes(view)){invalidateData();await load({background:true});showQuietUpdate('Research updated');}}catch{}},4500);}
function intFreshText(st){const job=st?.jobs?.find(j=>j.name==='ingestion');return job?.status==='running'?'Updating '+(job.cursor||'public data')+'…':job?.finished_at?'Updated '+intDate(job.finished_at)+(st.errors.length?' · Some sources unavailable':''):'Public data has not been refreshed yet';}
async function intWorkspace(){
  const generation=++INT.generation;const tab=INT.tab;
  $('#view').innerHTML=`<div class="stack-y int-workspace">${intNav()}<div class="int-top"><div><span class="label">Investment intelligence</span><div class="muted small" id="intFresh">Reading local research data…</div></div><button type="button" class="btn ghost sm" data-int-refresh="">Refresh data</button></div><div id="intBody">${skeleton()}</div><div id="intConnections"></div></div>`;intBind();
  try{
    const q=tab==='portfolio'?{account:INT.account,class:INT.cls}:tab==='research'?{symbol:INT.symbol}:tab==='insiders'?{symbol:INT.symbol && INT.filter==='company'?INT.symbol:''}:tab==='investors'?{cik:INT.manager}:{};
    const [status,data]=await Promise.all([intGet('status'),tab==='research' && !INT.symbol?Promise.resolve(null):intGet(tab,q)]);
    if(generation!==INT.generation || view!==intOwner(tab) || tab!==INT.tab)return;
    INT.status=status;INT.data=data;$('#intFresh').textContent=intFreshText(status);
    ({portfolio:intPortfolio,opportunities:intOpportunities,investors:intInvestors,insiders:intInsiders,watchlist:intWatchlist,research:intResearch,alerts:intAlerts})[tab](data);
    if($('#intConnections'))$('#intConnections').innerHTML=intConnections(status);intBind();intBindConnections();
    if(status.jobs.some(j=>j.status==='running'))intPoll();
  }catch(e){if(generation===INT.generation && $('#intBody'))$('#intBody').innerHTML=intCard('Data unavailable',intEmpty(e.message)+'<button type="button" class="btn ghost" data-int-refresh="">Try updating public data</button>');intBind();}
}
function intBars(rows,value='weight_pct',suffix='%'){
  return rows?.length?`<div class="int-bars">${rows.map((r,i)=>`<div><span>${esc(r.name||r.symbol)}</span><div class="int-track"><i style="width:${Math.max(0,Math.min(100,r[value]||0))}%;background:var(${SERIES[i%SERIES.length]})"></i></div><b>${intNum(r[value])}${suffix}</b></div>`).join('')}</div>`:intEmpty('No verified data for this selection.');
}
function intChart(slot,series,height=230,pctMode=false,unit=''){const el=$(slot);if(!el)return;if(!series.some(s=>s.pts?.length>1)){el.innerHTML=intEmpty('More historical observations are needed.');return;}timeChart(el,{series,height,unit,pct:pctMode?'index':false,label:'Persisted public market observations',sync:true});}
function intTable(headers,rows,render,id='intTable'){
  intTables.set(id,{rows,render});
  return `<div class="int-table-wrap"><table id="${id}"><thead><tr>${headers.map(([key,label])=>`<th><button type="button" class="linkish" data-int-sort="${esc(key)}">${esc(label)} ↕</button></th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(render).join(''):`<tr><td colspan="${headers.length}">${intEmpty('No observations match this selection.')}</td></tr>`}</tbody></table></div>`;
}
function intPortfolio(d){
  const risk=d.risk,c=d.concentration,g=d.gains;const accounts=[...new Set([...S.positions.map(p=>p.account),...S.savings.filter(s=>s.invest).map(s=>s.name),S.managed.name])];
  const controls=`<div class="controls"><select id="intClass" aria-label="Analysis asset class">${[['all','All investments'],['Stocks','Stocks'],['Funds','Funds'],['Bonds','Bonds'],['Crypto','Crypto'],['Alternatives','Alternatives'],['Cash & deposits','Cash & deposits']].map(([v,l])=>`<option value="${v}" ${INT.cls===v?'selected':''}>${l}</option>`).join('')}</select><select id="intAccount" aria-label="Analysis account"><option value="">All relevant accounts</option>${accounts.filter(n=>INT.cls==='all'||d.positions.some(p=>p.account===n)).map(n=>`<option ${n===INT.account?'selected':''}>${esc(n)}</option>`).join('')}</select></div>`;
  $('#intBody').innerHTML=`<div class="stack-y">${controls}<div class="int-metrics">${intMetric('Selected investments',eur(d.total))}${intMetric('Effective positions',intNum(c.effective_positions),'1 / security concentration index')}${intMetric('Largest security',intPct(c.largest_weight_pct),'Combined across accounts')}${intMetric('Top five',intPct(c.top5_weight_pct))}</div>
    ${d.warnings.length?intCard('Portfolio Doctor',d.warnings.map(w=>`<div class="list-row"><div><b>${esc(w.title)}</b><div class="muted small">${esc(w.detail)}</div></div><span class="tag">${esc(w.type)}</span></div>`).join('')+`<button class="linkish small" type="button" data-int-chat="Interpret my portfolio analysis. Explain the three most material risks using analyze_portfolio; separate data gaps from actual risks.">Discuss the findings</button>`):''}
    <div class="grid g2">${intCard('Asset allocation',intBars(d.allocations.asset_class))}${intCard('Sector exposure',intBars(d.allocations.sector))}${intCard('Geographic exposure',intBars(d.allocations.country),'Issuer domicile or imported region; not business revenue geography.')}${intCard('Currency exposure',intBars(d.allocations.currency),'Listing currency is a proxy. Unhedged funds may have different underlying exposure.')}</div>
    ${intCard('Covered holdings · performance & risk',`<div class="int-metrics">${intMetric('Annual volatility',intPct(risk.volatility_pct))}${intMetric('Maximum drawdown',intPct(risk.max_drawdown_pct))}${intMetric('Beta',intNum(risk.beta,2),'Against '+d.benchmark)}${intMetric('Sharpe / Sortino',intNum(risk.sharpe,2)+' / '+intNum(risk.sortino,2))}</div><div class="grid g2"><div><h4>Covered holdings · indexed</h4><div id="intCurve"></div></div><div><h4>Below the high</h4><div id="intDrawdown"></div></div></div><p class="muted small">${intPct(risk.coverage_pct)} of investment value covered · ${risk.observations} aligned daily returns · ${esc(risk.scope)}</p><p class="muted small">Risk-free assumption ${intPct(risk.risk_free_pct)}. ${esc(risk.risk_free_source)} Benchmark total return: ${intPct(risk.benchmark_return_pct)}; covered model: ${intPct(risk.total_return_pct)}.</p>`)}
    <div class="grid g2">${intCard('Cost basis & gains',`<div class="int-metrics">${intMetric('Recorded cost basis',eur(g.cost_basis))}${intMetric('Unrealized gain',sgn(g.unrealized))}${intMetric('Verified FIFO realized',g.realized==null?'—':sgn(g.realized))}${intMetric('Cost basis coverage',intPct(g.cost_coverage_pct))}</div>`,g.realized_scope)}${intCard('Valuation & style',`<p>Covered earnings yield <b>${intPct(d.valuation.earnings_yield_pct)}</b> · ${intPct(d.valuation.coverage_pct)} coverage</p>${intBars(d.style_exposure)}`,d.valuation.method+' '+d.methodology)}</div>
    <details class="card int-details"><summary>Fund look-through & hidden overlap <span class="muted small">${intPct(d.lookthrough_coverage_pct)} underlying value identified</span></summary>${intTable([['symbol','Security'],['direct','Direct'],['fund','Through funds'],['effective_weight_pct','Combined']],d.lookthrough,r=>`<tr><td>${intLink(r.symbol)}<div class="muted small">${esc(r.via.join(', '))}</div></td><td>${intPct(r.direct)}</td><td>${intPct(r.fund)}</td><td>${intPct(r.effective_weight_pct)}</td></tr>`,'intLook')}<p class="muted small">Partial disclosed top holdings only. Unknown fund holdings remain unallocated; totals are lower bounds.</p></details>
    <details class="card int-details"><summary>Correlation & contribution to risk</summary>${intHeatmap(d.correlations)}${intTable([['symbol','Security'],['weight_pct','Model weight'],['risk_share_pct','Risk share'],['mean_daily_return_contribution_bps','Mean daily contribution']],d.contributions,r=>`<tr><td>${intLink(r.symbol)}</td><td>${intPct(r.weight_pct)}</td><td>${intPct(r.risk_share_pct)}</td><td>${intNum(r.mean_daily_return_contribution_bps,2)} bps</td></tr>`,'intContribution')}<p class="muted small">Risk share = weight × covariance with covered portfolio / portfolio variance. Return contribution is arithmetic mean daily attribution; it is not a cumulative trading return.</p></details>
    ${intCard('Position weights',intTable([['name','Investment'],['value','Value'],['weight_pct','Weight'],['unrealized','Unrealized']],d.positions,r=>`<tr><td>${r.symbol?intLink(r.symbol):esc(r.name)}<div class="muted small">${esc(r.name)} · ${esc(r.account)}</div></td><td>${eur(r.value)}</td><td>${intPct(r.weight_pct)}</td><td>${r.unrealized==null?'—':sgn(r.unrealized)}</td></tr>`))}
    <details class="card int-details"><summary>Data coverage & methodology</summary><p class="muted small">${esc(d.methodology)}</p>${d.data_status.map(r=>`<div class="list-row"><span>${esc(r.name)}</span><span class="muted small">${esc(r.company)} · ${r.historical_prices} EUR prices</span></div>`).join('')}</details></div>`;
  $('#intClass').onchange=e=>{INT.cls=e.target.value;INT.account='';intWorkspace();};$('#intAccount').onchange=e=>{INT.account=e.target.value;intWorkspace();};
  intChart('#intCurve',[{name:'Covered portfolio model',pts:d.curve.map(r=>[tOf(r.date),r.value]),color:'var(--s1)',area:true},{name:d.benchmark,pts:d.curve.filter(r=>r.benchmark_value!=null).map(r=>[tOf(r.date),r.benchmark_value]),color:'var(--s2)'}]);
  intChart('#intDrawdown',[{name:'Drawdown %',pts:d.curve.map(r=>[tOf(r.date),r.drawdown_pct]),color:'var(--loss)',area:true}],230,false,'%');
}
function intHeatmap(rows){if(!rows.length)return intEmpty('At least 60 common daily returns are needed.');return `<div class="int-table-wrap"><table class="int-heatmap"><thead><tr><th></th>${rows.map(r=>`<th>${esc(r.symbol)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.symbol)}</th>${rows.map(c=>`<td title="Daily EUR return correlation" style="background:color-mix(in srgb,var(${r.values[c.symbol]<0?'--s2':'--s1'}) ${Math.min(40,Math.abs(r.values[c.symbol]||0)*40)}%,transparent)">${intNum(r.values[c.symbol],2)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function intBreakdown(sc){return `<details class="int-breakdown"><summary>Score components · ${intPct(sc.coverage_pct)} coverage</summary>${(sc.components||[]).map(c=>`<div class="int-component"><div><b>${esc(c.name)}</b><span>${intNum(c.score,0)} / 100 · ${intPct(c.coverage*100,0)} available</span></div><div class="int-track"><i style="width:${c.score||0}%"></i></div><details><summary class="muted small">How this is scored</summary>${c.evidence.map(e=>`<p class="small">${esc(e.label)}: <b>${intNum(e.value,3)}</b> → ${intNum(e.points,0)} points<br><span class="muted">${esc(e.rule)}</span></p>`).join('')}</details></div>`).join('')}<p class="muted small">${esc(sc.interpretation||'Insufficient data to rank this company.')}</p></details>`;}
function intOpportunities(d){
  const items=d.items.map(r=>({...r,rank:r.score.overall}));
  $('#intBody').innerHTML=`<div class="stack-y"><section class="card" data-card="opp-companies"><div class="card-head"><div><h2>Researched companies</h2><p class="sub">Quality, valuation and change, next to what you already own.</p></div><button class="btn ghost sm" data-int-tab="research">Research a company</button></div><div class="controls"><input type="search" id="intSearch" placeholder="Filter companies or signals" aria-label="Filter opportunities"><select id="intOppScope" aria-label="Opportunity scope"><option value="all">All researched companies</option><option value="held">Current holdings</option><option value="watched">Watchlist</option><option value="diversify">Improves diversification</option><option value="weak">Deteriorating earnings</option></select></div><div id="intOppRows"></div><p class="note">${esc(d.coverage)}</p></section></div>`;
  let sort='rank',desc=true;
  const draw=()=>{const q=$('#intSearch').value.toLowerCase(),scope=$('#intOppScope').value;const rows=items.filter(r=>(r.name+' '+r.symbol+' '+(r.signals||[]).join(' ')).toLowerCase().includes(q)).filter(r=>scope==='all'||scope==='held'&&r.held||scope==='watched'&&r.watched||scope==='diversify'&&r.portfolio_fit?.hhi_after<r.portfolio_fit?.hhi_before||scope==='weak'&&r.fundamentals?.earnings_growth<-.2).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name)*(desc?1:-1):((b[sort]??-Infinity)-(a[sort]??-Infinity))*(desc?1:-1));
    $('#intOppRows').innerHTML=intTable([['name','Company'],['rank','Opportunity'],['status','Freshness']],rows,r=>`<tr><td>${intLink(r.symbol)}${r.name&&r.name!==r.symbol?` <b>${esc(r.name)}</b>`:''}<div class="muted small">${[r.held?'Held':'',r.watched?'Watching':'',...(r.signals||[])].filter(Boolean).map(esc).join(' · ')}</div>${r.score.components?.length?intBreakdown(r.score):''}</td><td>${intScore(r.score)}${r.score.coverage_pct?`<div class="muted small">${intPct(r.score.coverage_pct,0)} coverage</div>`:''}${r.sparkline?.length?spark(r.sparkline,{w:96,h:28}):''}</td><td><span class="tag" title="${esc(r.reason||'')}">${esc(r.status)}</span>${r.metadata?.retrieved_at?`<div class="muted small">${intDate(r.metadata.retrieved_at)}</div>`:''}</td></tr>`);
    $$('[data-int-sort]').forEach(b=>b.onclick=()=>{desc=sort===b.dataset.intSort?!desc:true;sort=b.dataset.intSort;draw();});intBind();};
  $('#intSearch').oninput=draw;$('#intOppScope').onchange=draw;draw();
}
function intInvestors(d){
  const managers=d.managers,m=managers.find(m=>m.cik===INT.manager)||managers.find(m=>m.latest)||managers[0];if(m && !INT.manager){INT.manager=m.cik;intWorkspace();return;}
  const hist=m?.history||[];const quarter=INT.quarter||m?.latest?.period;const current=(hist.find(h=>h.period===quarter && h.holdings))||m?.latest;
  $('#intBody').innerHTML=`<div class="stack-y"><div class="int-intro"><h2>Disclosed conviction</h2><p class="muted">${esc(d.disclosure)}</p></div><div class="controls"><select id="intManager" aria-label="Tracked investor">${managers.map(r=>`<option value="${r.cik}" ${m?.cik===r.cik?'selected':''}>${esc(r.name)}</option>`).join('')}</select><select id="intQuarter" aria-label="Disclosure quarter">${hist.map(r=>`<option value="${esc(r.period)}" ${r.period===quarter?'selected':''}>${esc(r.period)} · filed ${intDate(r.filed)}</option>`).join('')}</select></div>
    ${current?`<div class="int-metrics">${intMetric('Disclosed value','$'+intNum(current.total_usd,0))}${intMetric('Positions',current.holdings.length)}${intMetric('Quarter end',esc(current.period))}${intMetric('Filed',intDate(current.filed))}</div><div class="grid g2">${intCard('Biggest weights',intBars(current.holdings.slice(0,8).map(r=>({...r,name:r.name}))))}${intCard('Biggest share changes',current.changes.filter(r=>r.move!=='unchanged').slice(0,7).map(r=>`<div class="list-row"><div><b>${esc(r.name)}</b><div class="muted small">${esc(r.cusip)} ${esc(r.option_type||'')}</div></div><span>${esc(r.move)} · ${intPct(r.change_pct)}</span></div>`).join('')||intEmpty('A previous full quarter is needed for changes.'))}</div>${intCard('Full disclosed portfolio',intTable([['name','Company / security'],['value','USD value'],['weight_pct','Weight'],['shares','Shares / principal']],current.holdings,r=>`<tr><td>${esc(r.name)}<div class="muted small">${esc(r.cusip)} · ${esc(r.share_type)} ${esc(r.option_type||'')}</div></td><td>$${intNum(r.value,0)}</td><td>${intPct(r.weight_pct)}</td><td>${intNum(r.shares,0)}</td></tr>`,'intManagerHoldings'), 'Weight is a disclosed-value proxy for conviction, not a verified investment intention.')}${intCard('All changes, including exits',intTable([['name','Company'],['move','Move'],['change_pct','Share change'],['weight_pct','Latest weight']],current.changes,r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.move)}</td><td>${intPct(r.change_pct)}</td><td>${intPct(r.weight_pct)}</td></tr>`,'intManagerChanges'),'Share-count changes can also reflect splits, mergers or reporting changes. Additions-only amendments remain stored without replacing a full quarter.')}<p class="muted small">${intURL(current.url,'Original SEC filing')}</p>`:intCard('Investor filings',intEmpty('No filings downloaded yet. Configure SEC identification in Settings → Connections, then refresh data.'))}
    ${intCard('Investor consensus',intTable([['name','Company'],['owner_count','Owners'],['average_weight_pct','Mean weight'],['adding','Adding / reducing']],d.consensus,r=>`<tr><td>${esc(r.name)}<div class="muted small">${esc(r.cusip)}</div></td><td>${r.owner_count}<div class="muted small">${esc(r.owners.join(', '))}</div></td><td>${intPct(r.average_weight_pct)}</td><td>${r.adding.length} / ${r.reducing.length}</td></tr>`,'intConsensus'),'Compared across latest available manager disclosures, which may cover different quarters.')}
    <details class="card int-details"><summary>Configure tracked investors</summary><form id="intManagerForm" class="controls"><input name="name" required placeholder="Investor / manager name" aria-label="Investor name"><input name="cik" required pattern="[0-9]{1,10}" placeholder="SEC CIK" aria-label="Manager SEC CIK"><button class="btn">Add investor</button></form>${managers.map(r=>`<div class="list-row"><span>${esc(r.name)} · CIK ${r.cik}</span><button class="linkish small" type="button" data-int-remove-manager="${r.cik}">Remove</button></div>`).join('')}</details></div>`;
  $('#intManager').onchange=e=>{INT.manager=e.target.value;INT.quarter='';intWorkspace();};$('#intQuarter').onchange=e=>{INT.quarter=e.target.value;intInvestors(d);intBind();};
  $('#intManagerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await intAction('manager',Object.fromEntries(f));};$$('[data-int-remove-manager]').forEach(b=>b.onclick=()=>intAction('manager',{cik:b.dataset.intRemoveManager,delete:true}));
}
function intInsiders(d){
  $('#intBody').innerHTML=`<div class="stack-y"><div class="int-intro"><h2>Insider activity</h2><p class="muted">Prioritise reported open-market transactions. Grants, derivatives and disclosed plans remain separately inspectable.</p></div><div class="int-metrics">${intMetric('Distinct buyers · 90d',d.summary.buyers)}${intMetric('Open-market purchases','$'+intNum(d.summary.buy_value_usd,0))}${intMetric('Open-market sales','$'+intNum(d.summary.sell_value_usd,0))}${intMetric('Buying clusters',d.summary.clusters.length)}</div><section class="card" data-card="int-insider-trades"><div class="card-head"><h2>Transactions</h2></div><div class="controls"><input type="search" id="intInsiderFilter" placeholder="Company, insider or role" aria-label="Filter insiders"><label class="check"><input type="checkbox" id="intGenuine" ${INT.genuine?'checked':''}> Open-market only</label></div><div id="intInsiderTable"></div></section><div class="grid g2">${intCard('Clusters & repeated purchases',d.summary.clusters.map(c=>`<div class="list-row"><span>${intLink(c.symbol)}</span><span>${c.buyers} buyers · $${intNum(c.value,0)}</span></div>`).join('')+d.summary.repeated_buyers.map(r=>`<div class="list-row"><span>${esc(r.insider)}</span><span>${r.purchases} purchases</span></div>`).join('')||intEmpty('No qualifying cluster has been recorded.'))}${intCard('Buying & selling over time','<div id="intInsiderTrend"></div>','Recorded open-market transactions only; a missing month is not evidence of zero activity.')}</div>${intCard('Purchases relative to company size',intTable([['symbol','Company'],['buy_value_usd','Purchases USD'],['market_cap_usd','Market cap USD'],['buy_to_market_cap_pct','Purchases / cap']],d.relative_size,t=>`<tr><td>${intLink(t.symbol)}</td><td>$${intNum(t.buy_value_usd,0)}</td><td>${t.market_cap_usd==null?'—':'$'+intNum(t.market_cap_usd,0)}</td><td>${intPct(t.buy_to_market_cap_pct,4)}</td></tr>`,'intInsiderSize'),'Latest recorded cap and FX compared with 90-day purchases; unavailable when currency cannot be verified.')}<p class="muted small">${esc(d.coverage)} ${esc(d.amendment_caveat)}</p></div>`;
  const draw=()=>{const q=$('#intInsiderFilter').value.toLowerCase();const trades=d.trades.filter(t=>(!INT.genuine||t.open_market)&&(t.symbol+' '+t.insider+' '+t.role).toLowerCase().includes(q));
    $('#intInsiderTable').innerHTML=intTable([['date','Transaction / filed'],['symbol','Company / insider'],['type','Classification'],['value','Value / price'],['shares','Shares / ownership after']],trades,t=>`<tr><td>${intDate(t.date)}<div class="muted small">Filed ${intDate(t.filed)}</div>${intURL(t.url,'Form 4')}</td><td>${intLink(t.symbol)}<div>${esc(t.insider)}</div><div class="muted small">${esc(t.role)}</div></td><td><span class="tag">${esc(t.type)}</span><div class="muted small">${esc(t.classification)}</div>${t.footnotes?`<details><summary class="small">Footnotes</summary><p class="small">${esc(t.footnotes)}</p></details>`:''}</td><td>${t.value==null?'—':'$'+intNum(t.value,0)}<div class="muted small">$${intNum(t.price,2)} / share</div></td><td>${intNum(t.shares,0)}<div class="muted small">After ${intNum(t.ownership_after,0)} · ${esc(t.ownership_type)}</div></td></tr>`);intBind();};$('#intGenuine').onchange=e=>{INT.genuine=e.target.checked;draw();};$('#intInsiderFilter').oninput=draw;draw();
  intChart('#intInsiderTrend',[{name:'Purchases USD',pts:d.trend.map(r=>[tOf(r.month+'-01'),r.buy_value_usd]),color:'var(--gain)'},{name:'Sales USD',pts:d.trend.map(r=>[tOf(r.month+'-01'),r.sell_value_usd]),color:'var(--loss)'}],190,false,'$');
}
function intWatchlist(d){
  const opps=new Map(d.opportunities.map(r=>[r.symbol,r]));
  $('#intBody').innerHTML=`<div class="stack-y"><div class="int-intro"><h2>Your research radar</h2><p class="muted">Follow meaningful changes in valuation, reported growth, filings and ownership.</p></div><form id="intWatchForm" class="controls"><input name="symbol" required placeholder="Ticker, e.g. ASML.AS" aria-label="Watchlist ticker"><input name="name" placeholder="Company name" aria-label="Company name"><input name="thesis" placeholder="Why you are watching" aria-label="Investment thesis"><button class="btn">Add to watchlist</button></form><button class="linkish small" data-int-chat="What changed in my watchlist this week? Use get_watchlist, get_opportunities and recent filings. Which thesis weakened, and which valuation became more attractive? Distinguish measured changes from interpretation.">Discuss this week’s changes</button>
    ${d.items.length?d.items.map(w=>{const r=opps.get(w.symbol)||{};const f=r.fundamentals||{};const changes=Object.entries(r.changes||{});return intCard(w.name||w.symbol,`<div class="int-watch-head"><div>${intLink(w.symbol)} <span class="tag">${esc(r.status||'Awaiting data')}</span><p class="muted small">${esc(w.thesis||w.note||'No thesis recorded yet.')}</p></div><div>${intScore(r.score)} ${r.sparkline?.length?spark(r.sparkline,{w:120,h:32}):''}</div></div><div class="int-metrics">${intMetric('Trailing P/E',intRatio(f.trailing_pe))}${intMetric('Revenue growth',intPct(f.revenue_growth==null?null:f.revenue_growth*100))}${intMetric('Below 52w high',intPct(f.drawdown_52w==null?null:f.drawdown_52w*100))}${intMetric('Portfolio fit',intNum(r.portfolio_fit?.score,0)+' / 100')}</div>${changes.length?`<details><summary>Measured changes since previous snapshot</summary>${changes.map(([k,c])=>`<div class="list-row"><span>${esc(k.replaceAll('_',' '))}</span><span>${intNum(c.before,3)} → ${intNum(c.now,3)}</span></div>`).join('')}</details>`:'<p class="muted small">A second dated snapshot is needed to measure change.</p>'}<div class="controls"><button class="linkish small" type="button" data-int-refresh="${esc(w.symbol)}">Update</button><button class="linkish small" type="button" data-int-company="${esc(w.symbol)}">Deep research</button><button class="linkish small" type="button" data-int-remove-watch="${esc(w.symbol)}">Remove</button></div>`);}).join(''):intCard('Start your watchlist',intEmpty('Add a company symbol and a short thesis. Public data will be retained locally.'))}
    ${intCard('Watchlist signals',d.alerts.items.filter(s=>d.items.some(w=>w.symbol===s.symbol)).slice(0,20).map(s=>`<div class="list-row"><div><b>${esc(s.title)}</b><div class="muted small">${esc(s.symbol)} · ${esc(s.detail)}</div></div><span class="muted small">${intDate(s.created_at)}</span></div>`).join('')||intEmpty('No meaningful changes have been recorded.'))}</div>`;
  $('#intWatchForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await post('/api/intelligence/watchlist',body);await post('/api/intelligence/refresh',{symbol:body.symbol});intWorkspace();intPoll();}catch(e){toast(e.message);}};$$('[data-int-remove-watch]').forEach(b=>b.onclick=()=>intAction('watchlist',{symbol:b.dataset.intRemoveWatch,delete:true}));
}
function intResearch(r){
  const s=INT.symbol;const search=`<form id="intResearchSearch" class="controls"><input id="intTicker" placeholder="Research a ticker, e.g. ASML.AS" value="${esc(s)}" aria-label="Research company symbol" required><button class="btn">Open research</button></form>`;
  if(!r || r.status==='unavailable'){$('#intBody').innerHTML=`<div class="stack-y">${search}${intCard('Company research',intEmpty(r?.reason||'Enter a market ticker to open its financials, filings and research workspace.')+(s?`<button class="btn ghost" data-int-refresh="${esc(s)}">Retrieve ${esc(s)} data</button>`:''))}</div>`;intResearchSearch();return;}
  const f=r.fundamentals,info=r.metadata,thesis=r.thesis||{},cases=thesis.cases||[];
  const questions=[['Overview',`Analyse ${s} for me. Explain its business model, revenue segments, geographic revenue, moat, competitors, management, capital allocation, growth, profitability, cash flow, debt, valuation and portfolio fit. Use the investment tools for figures and sources for business claims.`],['Latest earnings',`Summarize the latest earnings for ${s}. What changed since the prior quarter? Use filings and current sources, identify guidance or estimate revisions, and distinguish reporting periods.`],['Bear case',`Give me the strongest argument against buying ${s}. What could make the thesis fail? Identify competitors, balance sheet risks and thesis-changing developments with sources.`],['Committee',`Run an Investment Committee review of ${s}. Use the company tools, analyze_portfolio and calculate_portfolio_fit. Give separate Bull Case, Bear Case, Valuation Case, Risk Case, Portfolio Fit, Smart Money Activity and Insider Activity sections, then a concise synthesis of disagreements and unknowns. Never invent metrics or one objectively correct recommendation. Scenarios must come from the saved backend calculations.`]];
  $('#intBody').innerHTML=`<div class="stack-y">${search}<div class="int-company-head"><div><span class="label">${esc(s)} · ${esc(r.industry||'Industry unavailable')}</span><h2>${esc(r.name)}</h2><span class="muted small">${esc(info.source)} · retrieved ${intDate(info.retrieved_at)} · ${esc(r.status)} · ${esc(f.currency||'Currency unavailable')}</span></div><div>${intScore(r.score)}</div></div><div class="int-metrics">${intMetric('Price',intNum(f.price,2)+' '+esc(f.currency||''),'Delayed / provider quote')}${intMetric('Trailing / forward P/E',intRatio(f.trailing_pe)+' / '+intRatio(f.forward_pe))}${intMetric('Market cap',intNum(f.market_cap,0)+' '+esc(f.currency||''))}${intMetric('Free cash flow yield',intPct(f.fcf_yield==null?null:f.fcf_yield*100))}</div>
    <div class="controls">${questions.map(([label,q])=>`<button class="btn ghost sm" type="button" data-int-chat="${esc(q)}">${label}</button>`).join('')}<button class="linkish small" type="button" data-int-refresh="${esc(s)}">Update company</button></div>
    ${intCard('Business overview',`<p class="int-business">${esc(r.overview||'No company overview available from the current provider.')}</p>`+intURL(r.website,'Company website'))}
    <div class="grid g2">${intCard('Fundamentals',`<div class="int-metrics">${intMetric('Revenue growth',intPct(f.revenue_growth==null?null:f.revenue_growth*100))}${intMetric('Earnings growth',intPct(f.earnings_growth==null?null:f.earnings_growth*100))}${intMetric('Net / operating margin',intPct(f.profit_margin==null?null:f.profit_margin*100)+' / '+intPct(f.operating_margin==null?null:f.operating_margin*100))}${intMetric('ROIC / ROE',intPct(f.roic==null?null:f.roic*100)+' / '+intPct(f.roe==null?null:f.roe*100))}${intMetric('Net debt',intNum(f.net_debt,0)+' '+esc(f.financial_currency||''))}${intMetric('Free cash flow',intNum(f.fcf,0)+' '+esc(f.financial_currency||''))}</div><div id="intRevenueChart"></div>`,f.source_note+' Latest annual statement: '+(f.period||'unavailable'))}${intCard('Opportunity components',intBreakdown(r.score))}</div>
    <div class="grid g2">${intCard('Portfolio fit',`<p>A hypothetical ${intPct(r.portfolio_fit.allocation_pct)} allocation moves concentration from <b>${intNum(r.portfolio_fit.hhi_before,3)}</b> to <b>${intNum(r.portfolio_fit.hhi_after,3)}</b>.</p>${Object.entries(r.portfolio_fit.exposures).map(([k,v])=>v?`<div class="list-row"><span>${esc(v.name)} · ${esc(k)}</span><span>${intPct(v.before_pct)} → ${intPct(v.after_pct)}</span></div>`:'').join('')}<p class="muted small">Historical blend volatility ${intPct(r.portfolio_fit.modeled_volatility_before_pct)} → ${intPct(r.portfolio_fit.modeled_volatility_after_pct)}; correlation ${intNum(r.portfolio_fit.correlation_to_portfolio,2)}. ${esc(r.portfolio_fit.risk_model_scope)}</p>`,r.portfolio_fit.assumption)}${intCard('Ownership & insiders',`<p>Tracked investors: ${r.smart_money.owners?.length?esc(r.smart_money.owners.join(', ')):esc(r.smart_money.coverage)}</p><p>${r.insiders.score==null?'Insider disclosure coverage unavailable.':r.insiders.buyers+' distinct open-market buyers · $'+intNum(r.insiders.buy_value_usd,0)+' in 90 days.'}</p><div class="controls"><button class="linkish small" data-int-tab="investors">Investor disclosures</button><button class="linkish small" data-int-tab="insiders">Insider transactions</button></div>`)}</div>
    ${intCard('Valuation over recorded history','<div id="intValuationChart"></div>','Actual retrieved valuation snapshots, not reconstructed historical P/E. A second dated observation is needed for a line.')}
    ${intCard('Recent developments',r.news.slice(0,10).map(n=>`<div class="list-row"><div>${intURL(n.url,n.title||'Company news')}<div class="muted small">${esc(n.source||'')} · ${intDate(n.date)}</div></div></div>`).join('')||intEmpty('No provider news returned. Ask Latest earnings to research original company sources.'))}
    <details class="card int-details"><summary>Recent filings & source evidence</summary>${r.filings.length?r.filings.slice(0,30).map(x=>`<div class="list-row"><span>${intURL(x.url,x.form+' · '+x.filingDate)}</span><span class="muted small">Report ${esc(x.reportDate||'—')}</span></div>`).join(''):intEmpty('No SEC issuer filings downloaded. Configure SEC identification or use company investor relations.')}<p class="muted small">${esc(r.sec?.data?.coverage||'')}</p></details>
    <details class="card int-details"><summary>Financial statements, estimates & alternative datasets</summary>${intDatasetHtml(r)}</details>
    ${intCard('Thesis & scenario assumptions',`<form id="intThesisForm"><label class="label" for="intThesisNotes">Investment thesis / developments to monitor</label><textarea id="intThesisNotes" rows="4" placeholder="Your bull, base and bear thesis; what would change your mind">${esc(thesis.notes||'')}</textarea><label class="label" for="intCusip">Verified CUSIP for 13F matching (optional)</label><input id="intCusip" maxlength="9" placeholder="9-character CUSIP" value="${esc(r.smart_money.cusip||'')}"><div class="int-scenarios">${['Bear','Base','Bull'].map((name,i)=>{const c=cases.find(c=>c.name===name)||{};return `<fieldset><legend>${name}</legend><label>Years<input type="number" min="1" max="30" data-case="${i}" data-field="years" value="${c.years||5}" required></label><label>Annual EPS growth %<input type="number" step="0.1" min="-99" max="200" data-case="${i}" data-field="growth_pct" value="${c.growth_pct??''}" required></label><label>Exit P/E<input type="number" step="0.1" min="0.1" max="200" data-case="${i}" data-field="exit_pe" value="${c.exit_pe??''}" required></label><label>Annual dividend / share<input type="number" step="0.01" min="0" data-case="${i}" data-field="annual_dividend" value="${c.annual_dividend||0}" required></label></fieldset>`;}).join('')}</div><button class="btn">Save & calculate scenarios</button></form>${thesis.computed?.length?intTable([['name','Case'],['terminal_price','Terminal price'],['cagr_pct','Annualised return']],thesis.computed,c=>`<tr><td>${esc(c.name)}</td><td>${intNum(c.terminal_price,2)} ${esc(c.currency||'')}</td><td>${intPct(c.cagr_pct)}</td></tr>`,'intScenarios'):''}<p class="muted small">User assumptions, not forecasts. Backend calculations use current trailing EPS, assumed growth, exit multiple and constant cash dividends; no reinvestment. Unavailable for nonpositive EPS.</p>`)}
    <p class="muted small">${r.unavailable.map(esc).join(' ')}</p></div>`;
  intResearchSearch();$('#intThesisForm').onsubmit=async e=>{e.preventDefault();const cases=['Bear','Base','Bull'].map((name,i)=>({name,...Object.fromEntries($$(`[data-case="${i}"]`).map(x=>[x.dataset.field,+x.value]))}));await intAction('thesis',{symbol:s,notes:$('#intThesisNotes').value,cusip:$('#intCusip').value,cases});};
  const annual=r.statements.income||[];intChart('#intRevenueChart',[{name:'Annual revenue',pts:[...annual].reverse().filter(x=>x.items['Total Revenue']!=null).map(x=>[tOf(x.period),x.items['Total Revenue']]),color:'var(--s1)'}],180,false,f.financial_currency||'');
  intChart('#intValuationChart',[{name:'Trailing P/E',pts:[...r.valuation_history].reverse().filter(x=>x.trailing_pe!=null).map(x=>[new Date(x.retrieved_at).getTime(),x.trailing_pe]),color:'var(--s2)'}],210,false,'×');
}
function intResearchSearch(){$('#intResearchSearch').onsubmit=e=>{e.preventDefault();INT.symbol=$('#intTicker').value.trim().toUpperCase();store.set('int.symbol',INT.symbol);intWorkspace();};}
function intDatasetHtml(r){const datasets={Statements:r.statements,'Analyst estimates':r.analyst_estimates,'SEC annual statements':r.sec_statements?.data,'Estimate revisions':r.estimate_changes,'Institutional holders':r.institutional_ownership,OpenBB:r.openbb?.data,'Quiver alternative data':Object.fromEntries(Object.entries(r.alternative).filter(([,v])=>v).map(([k,v])=>[k,{source:v.source,retrieved_at:v.retrieved_at,data:v.data}]))};return Object.entries(datasets).map(([label,value])=>`<details><summary>${esc(label)}</summary>${value&&Object.keys(value).length?`<pre class="int-json">${esc(JSON.stringify(value,null,2))}</pre>`:intEmpty('Unavailable from the configured provider or credentials.')}</details>`).join('');}
const INT_ALERT_NAMES={concentration:'Position concentration %',new_position:'New investor position',investor_add:'Investor share increase %',consensus:'Investors adding same company',insider_buy:'Open-market purchase USD',cluster_buy:'Distinct insider buyers',insider_sell:'Open-market sales USD',valuation:'Trailing P/E below threshold',price_drop:'Below 52-week high %',filing:'Material company filing',earnings_change:'Earnings growth change, percentage points',estimate_change:'Analyst revision balance change, points',news:'Company news to review',investor_exit:'Investor exit disclosure'};
function intAlerts(d){
  $('#intBody').innerHTML=`<div class="stack-y"><div class="int-intro"><h2>Signals that deserve attention</h2><p class="muted">Configurable, source-grounded alerts from saved observations. ${esc(d.delivery)}</p></div>${intCard('Activity',d.items.length?d.items.map(s=>`<div class="list-row"><div><b>${esc(s.title)}</b> ${s.seen?'':'<span class="tag">New</span>'}<div class="muted small">${esc(s.symbol)} · ${esc(s.detail)}</div><div class="muted small">${intDate(s.created_at)}${JSON.parse(s.payload||'{}').url?' · '+intURL(JSON.parse(s.payload).url,'Source'):''}</div></div><button class="linkish small" data-int-seen="${s.id}">Mark read</button></div>`).join(''):intEmpty('No alerts yet. Signals appear after data updates and threshold crossings.'))}
    <details class="card int-details" open><summary>Alert rules</summary><form id="intRuleForm" class="controls"><select name="type" aria-label="Alert type">${Object.entries(INT_ALERT_NAMES).map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}</select><input name="symbol" placeholder="Ticker (optional)" aria-label="Alert symbol"><input type="number" name="threshold" min="0" value="20" step="0.1" aria-label="Alert threshold"><button class="btn">Save rule</button></form>${d.rules.map(r=>`<div class="list-row"><span>${esc(INT_ALERT_NAMES[r.type])}${r.symbol?' · '+esc(r.symbol):''}<div class="muted small">Threshold ${intNum(r.threshold)}${r.type==='valuation'?' · Lower P/E triggers':' · At or above triggers'}</div></span><label class="check"><input type="checkbox" data-int-rule="${r.id}" ${r.enabled?'checked':''}> Enabled</label></div>`).join('')}</details></div>`;
  $('#intRuleForm').onsubmit=e=>{e.preventDefault();intAction('rule',Object.fromEntries(new FormData(e.target)));};$$('[data-int-rule]').forEach(b=>b.onchange=()=>{const r=d.rules.find(r=>r.id===b.dataset.intRule);intAction('rule',{...r,enabled:b.checked});});$$('[data-int-seen]').forEach(b=>b.onclick=()=>intAction('seen',{ids:[b.dataset.intSeen]}));
}
async function intAction(name,body){try{await post('/api/intelligence/'+name,body);toast('Saved');await load();if(view==='holdings')intWorkspace();else if(view==='explore')intWorkspace();else if(view==='settings')settings();}catch(e){toast(e.message);}}
function intConnections(st){const c=st.connections;return `<details class="card int-details"><summary>Data connections & coverage <span class="muted small">${st.company_count} companies · ${st.filing_count} filings</span></summary><p class="muted small">${esc(st.storage)}</p><div class="int-metrics">${intMetric('Market data',esc(c.market),'Yahoo fallback, delayed')}${intMetric('SEC EDGAR',c.sec_configured?'Configured':'Contact email needed')}${intMetric('OpenBB',c.openbb_installed?'Installed':'Optional installation needed')}${intMetric('Quiver',c.quiver_configured?'Configured':'Optional API key')}</div><form id="intConnectionsForm"><div class="grid g2"><label>SEC identification (app name + contact email)<input name="sec_user_agent" placeholder="WealthDashboard contact@example.com" autocomplete="off"></label><label>Quiver API key (optional)<input type="password" name="quiver_api_key" autocomplete="new-password" placeholder="${c.quiver_configured?'Saved locally; blank keeps it':'Optional API key'}"></label><label>Market adapter<select name="intelligence_market_provider">${['auto','yahoo','openbb'].map(v=>`<option ${c.market===v?'selected':''}>${v}</option>`).join('')}</select></label><label>OpenBB data provider<input name="openbb_data_provider" value="${esc(c.openbb_provider)}"></label><label>Benchmark ticker (returns converted to EUR)<input name="intelligence_benchmark" placeholder="IWDA.AS"></label><label>Annual risk-free assumption %<input name="intelligence_risk_free_pct" type="number" min="-5" max="30" step="0.1" placeholder="0"></label><label>Refresh interval (hours)<input name="intelligence_refresh_hours" type="number" min="1" max="168" placeholder="6"></label></div><button class="btn">Save connections</button>${c.quiver_configured?'<button type="button" class="btn ghost" id="intClearQuiver">Remove Quiver key</button>':''}</form>${st.errors.length?`<details><summary>Unavailable sources (${st.errors.length})</summary>${st.errors.map(e=>`<p class="muted small">${esc(e)}</p>`).join('')}</details>`:''}<p class="muted small">Saving SEC identification allows that contact email to be sent to SEC with public-data requests. SEC can restrict access. OpenBB datasets depend on the installed version/provider; Quiver datasets depend on your subscription. Cached history remains available when sources are unavailable.</p></details>`;}
function intBindConnections(){const form=$('#intConnectionsForm');if(form)form.onsubmit=async e=>{e.preventDefault();const body={};for(const [k,v] of new FormData(form))if(v.trim())body[k]=v.trim();await intAction('connections',body);};if($('#intClearQuiver'))$('#intClearQuiver').onclick=()=>intAction('connections',{clear_quiver:true});}
function investmentBadge(p){const s=p.symbol||(p.source && !['manual','last known'].includes(p.source)?p.source:null);const b=S?.intelligence?.badges?.[s];return b?.score!=null?` <button type="button" class="tag int-holding-badge" data-int-company="${esc(s)}" title="Explainable score ${intNum(b.score,0)}/100; ${intPct(b.coverage_pct,0)} coverage; ${esc(b.status)}${b.insider_buyers?'; '+b.insider_buyers+' insider buyers':''}${b.tracked_owners?'; '+b.tracked_owners+' tracked owners':''}">Research ${intNum(b.score,0)}</button>`:'';}
function intelligenceHome(){const d=S?.intelligence;if(!d)return '';const signals=d.signals||[];const risks=d.risks||[];return signals.length||risks.length?`<section class="card" id="intHome"><div class="card-head"><h2>Investment intelligence</h2><button type="button" class="linkish small" data-int-tab="alerts">${d.unread} signals</button></div>${risks.slice(0,1).map(r=>`<div class="list-row"><div><b>${esc(r.title)}</b><div class="muted small">${esc(r.detail)}</div></div></div>`).join('')}${signals.slice(0,2).map(s=>`<div class="list-row"><div><b>${esc(s.title)}</b><div class="muted small">${esc(s.detail)}</div></div></div>`).join('')}</section>`:'';}
const originalOpenHolding=openHolding;openHolding=async function(id){await originalOpenHolding(id);const p=S.positions.find(p=>posId(p)===id);const s=p?.symbol||(p?.source && !['manual','last known'].includes(p.source)?p.source:null);const slot=$('#hdFund');if(s && slot){slot.insertAdjacentHTML('beforebegin',`<div class="controls"><button type="button" class="btn ghost sm" id="intHoldingResearch">Investment research · ${esc(s)}</button></div>`);$('#intHoldingResearch').onclick=()=>{closeDrawer();intNavigate('research',s);};}};
const originalSearchIndex=searchIndex;searchIndex=function(){const rows=originalSearchIndex();for(const [s,b] of Object.entries(S?.intelligence?.badges||{})){if(b.score!=null)rows.push({type:'Research',name:s,sub:`Score ${intNum(b.score,0)} · ${intPct(b.coverage_pct,0)} coverage${b.insider_buyers?' · Insider buying':''}${b.tracked_owners?' · '+b.tracked_owners+' tracked owners':''}`,base:3,run:()=>intNavigate('research',s)});}return rows;};
const originalOverview=overview;overview=function(){originalOverview();const ask=$('#askbar');if(ask)ask.insertAdjacentHTML('afterend',intelligenceHome());intBind();};
const originalSettings=settings;settings=function(){originalSettings();if(!$('#intSettingsConnections'))$('#view').insertAdjacentHTML('beforeend','<div id="intSettingsConnections"></div>');intGet('status').then(st=>{if(view==='settings'&&$('#intSettingsConnections')){$('#intSettingsConnections').innerHTML=intConnections(st);intBindConnections();}}).catch(()=>{});};
const originalRenderChrome=renderChrome;renderChrome=function(){originalRenderChrome();let b=$('#intNotification');if(!b){$('.topbar .tools').insertAdjacentHTML('beforeend','<button type="button" id="intNotification" class="icon-btn" title="Investment signals" aria-label="Investment signals">◇</button>');b=$('#intNotification');b.onclick=()=>intNavigate('alerts');}b.textContent='◇'+(S?.intelligence?.unread?' '+S.intelligence.unread:'');};
