'use strict';
TITLES.setup='Setup & help';
let SETUP=null;
const profileRender=renderView;
renderView=function(){if(view==='setup')return renderSetup();return profileRender();};
async function setupStatus(){SETUP=await cachedJSON('/api/setup/status',{ttl:5000,force:true});paintProfileBar();return SETUP;}
function paintProfileBar(){
  if(!SETUP)return;let bar=$('#profileBar');if(!bar){bar=document.createElement('div');bar.id='profileBar';$('.topbar').after(bar);}
  bar.className='profile-bar '+SETUP.mode;bar.innerHTML=`<span><b>${SETUP.mode==='demo'?'Demo · fictional data':'Personal · your local data'}</b>${SETUP.mode==='demo'?' · disconnected sample workspace':''}</span><a href="#setup">${SETUP.mode==='demo'?'Use my own data':'Setup & connections'}</a><a href="/guide.html" target="_blank" rel="noopener">Installation guide ↗</a>`;
}
async function renderSetup(){
  $('#view').innerHTML='<div class="card"><h2>Setup & help</h2><p>Reading this workspace’s setup…</p></div>';
  try{await setupStatus();if(view!=='setup')return;
    const demo=SETUP.mode==='demo';$('#view').innerHTML=`<div class="stack-y setup-page"><section class="card"><h2>${demo?'Try it first, then make it yours':'Your own dashboard'}</h2><p>${demo?'This workspace contains invented investments, payments, cash, debts, plans, invoices and history. Your own workspace starts empty in a different folder.':'Your data is separate from the demo. Enable optional services only when you want them, then import your own records.'}</p><div class="setup-actions">${demo?'<button class="btn primary" id="usePersonal">Start my personal workspace</button>':'<a class="btn" href="#import">Import my records</a><a class="btn ghost" href="#settings">Provider settings</a>'}<a class="btn ghost" href="/guide.html" target="_blank" rel="noopener">Read the full guide</a></div><div id="setupMessage" role="status"></div></section>
    ${demo?`<div class="grid g2"><section class="card"><h2>A quick tour</h2><ol><li>Overview: compare net worth, spending and investments.</li><li>Investments: change asset class, account and chart range.</li><li>Savings & debt: inspect accounts, rates and a repayment scenario.</li><li>Spending: click a category and sort the payment popup.</li><li>Explore: search ASML.AS for a fictional company dossier.</li><li>Receipts: inspect the linked example invoice.</li></ol></section><section class="card"><h2>Try an import</h2><p>The included CSV is deliberately labelled DEMO ONLY. Download it and upload it on Import. Real documents belong in your personal workspace.</p><a class="btn ghost" href="/samples/demo-bank-transactions.csv" download>Download sample CSV</a><p>Chat replies and briefings in demo mode are illustrative saved examples; no external AI service is used.</p></section></div>`:
    `<section class="card"><h2>Choose optional connections</h2><p>Install the optional features first with <code>python install.py</code> in the downloaded project folder. Public data does not require an AI subscription. Provider accounts and limits remain separate.</p><form id="setupPreferences"><label><input type="checkbox" name="public_data_enabled" ${SETUP.public_data_enabled?'checked':''}> Live public data: prices, company research and flexible savings rates</label><label><input type="checkbox" name="ai_enabled" ${SETUP.ai_enabled?'checked':''}> AI: allow my configured Claude, ChatGPT-plan or local-model connection</label><label><input type="checkbox" name="cloud_enabled" ${SETUP.cloud_enabled?'checked':''}> Supabase: allow my separately configured cloud copy</label><button class="btn primary">Save choices & restart this workspace</button></form><p>After restart, use Settings to sign in or enter your own connection details. No connection is copied from the demo or the author.</p></section><div class="grid g2"><section class="card"><h2>Your first records</h2><ol><li>Import a current bank statement or supported CSV.</li><li>Import broker holdings and complete execution history.</li><li>Upload invoices to link purchases to existing payments.</li><li>Add confirmed savings balances and rates.</li><li>Add debt statements and confirmed repayment terms.</li><li>Review matches and duplicate warnings; use Undo when needed.</li></ol></section><section class="card"><h2>Keep your data safe</h2><p>Local folder: <code>${esc(SETUP.data_folder)}</code>. It is ignored by Git. Export an encrypted portable backup before replacing computers or major updates.</p><a class="btn ghost" href="#backups">Backups</a><a class="btn ghost" href="#connections">Connections & coverage</a><p>Share the public repository or its ZIP. Never share your personal runtime, credentials, statements or financial exports.</p></section></div>`}</div>`;
    if(demo)$('#usePersonal').onclick=async e=>{e.currentTarget.disabled=true;$('#setupMessage').textContent='Creating or reopening your separate personal workspace…';try{const result=await post('/api/setup/personal',{});location.href=result.url;}catch(error){$('#setupMessage').textContent=error.message;e.currentTarget.disabled=false;}};
    else $('#setupPreferences').onsubmit=async e=>{e.preventDefault();const form=e.target,body={};for(const key of ['public_data_enabled','ai_enabled','cloud_enabled'])body[key]=form.elements[key].checked;try{await post('/api/setup/preferences',body);$('#setupMessage').textContent='Restarting your personal workspace. This page will reopen shortly.';setTimeout(()=>location.reload(),2500);}catch(error){$('#setupMessage').textContent=error.message;}};
  }catch(error){$('#view').innerHTML='<div class="card"><h2>Setup help</h2><p>'+esc(error.message)+'</p><a href="/guide.html">Open the installation guide</a></div>';}
}
$('#nav a[href="#settings"]').insertAdjacentHTML('beforebegin','<a href="#setup"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 10v6M12 7h.01"/></svg>Setup & help</a>');
setupStatus().catch(()=>{});
