'use strict';
/* Adds connected workflows while retaining the existing dashboard, charts and AI logos. */
const WS={tab:store.get('ws.tab','cashflow'),generation:0,filter:'all',q:'',month:today().slice(0,7),account:store.get('ws.account',''),period:store.get('ws.period',{from:'',to:''}),summary:null,schemas:null,categories:[],data:null,searchGeneration:0,notifications:store.get('ws.notifications',false)};
const WS_TABS=[['cashflow','Cash flow'],['performance','Performance'],['research','Research desk'],['planning','Planning'],['documents','Documents'],['connections','Connections'],['backups','Backups']];
const wsScope=s=>s?`<p class="ws-scope">${esc(s)}</p>`:'';
const wsEmpty=s=>`<div class="empty">${esc(s)}</div>`;
const wsButton=(label,action,id='',extra='')=>`<button type="button" class="btn ghost sm" data-ws-action="${esc(action)}" data-ws-id="${esc(id)}" ${extra}>${esc(label)}</button>`;
const wsAdd=(kind,label)=>wsButton(label||'Add '+kind,'add',kind);
const wsChart=(id,label,rows,key,unit='€')=>{const box=$('#'+id);if(box)timeChart(box,{series:[{name:label,pts:rows.filter(r=>Number.isFinite(r[key])).map(r=>[tOf(r.date||r.month),r[key]])}],unit,height:230,select:true});};
function wsTable(columns,rows,limit=100){return rows?.length?`<div class="ws-table"><table><thead><tr>${columns.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,limit).map(r=>`<tr>${columns.map(([k,,format])=>`<td class="ws-cell-detail">${format?format(r[k],r):esc(r[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${rows.length>limit?wsScope(`Showing ${limit} of ${rows.length} records. Export or use search to inspect the rest.`):''}`:wsEmpty('No records available yet.');}
async function wsGet(name,q={}){return cachedJSON('/api/workspace/'+name+'?'+new URLSearchParams(q),{ttl:name==='summary'?30000:60000});}
async function wsPost(name,data={}){return post('/api/workspace/'+name,data);}
function wsNavigate(tab){WS.tab=tab;store.set('ws.tab',tab);if(view!=='explore')location.hash='explore';else workspacePage();}
function wsOpenReceipt(){SP.tab='receipts';if(view!=='spending')location.hash='spending';else spendingPage();}
function wsOpenPayment(id){ensureSpending().then(()=>txSheet(id)).catch(e=>toast(e.message));}
function wsRecordRows(kind,rows){return rows.length?rows.map(r=>`<div class="ws-row"><div><h3>${esc(r.name||r.account||r.instrument||kind)}</h3><div class="muted small">${esc(r.note||r.thesis||r.text||r.status||r.date||r.due||'Saved locally')}</div></div><div class="controls">${wsButton('Edit','edit',r.id,`data-ws-kind="${esc(kind)}"`)}${wsButton('Remove','delete',r.id,`data-ws-kind="${esc(kind)}"`)}</div></div>`).join(''):wsEmpty('Nothing saved yet.');}
function wsRecordCard(kind,title,rows,note=''){return intCard(title,`<div class="ws-list">${wsRecordRows(kind,rows)}</div><div class="controls">${wsAdd(kind,'Add '+title.toLowerCase())}</div>`,note);}
async function wsSchemas(){if(!WS.schemas){const d=await wsGet('schemas');WS.schemas=d.schemas;WS.categories=d.categories;}return WS.schemas;}
async function wsEdit(kind,ident='',seed={}){
  await wsSchemas();const schema=WS.schemas[kind];if(!schema)return toast('This record type is unavailable.');
  let item=seed;if(ident){const d=await wsGet('records',{kind});item=d.items.find(r=>r.id===ident)||seed;}
  const choices=await wsGet('choices');
  const fields=Object.entries(schema).map(([key,f])=>{const v=item[key]??(f.type==='checkbox'?['active','enabled'].includes(key):f.type==='date'&&key==='date'?today():'');const attrs=`name="${esc(key)}" ${f.required?'required':''}`;
    let opts=null;
    if(key==='account')opts=choices.accounts.map(x=>[x,x]);
    if(key==='source_id')opts=choices.sources.map(x=>[x.id,x.label]);
    if(key==='document_id')opts=choices.invoices.map(x=>[x.id,x.label]);
    if(key==='item_id')opts=choices.products.filter(x=>!item.document_id||x.document_id===item.document_id).map(x=>[x.id,x.label]);
    if(['transaction_id','received_transaction_id'].includes(key))opts=choices.payments.filter(x=>kind!=='refund'&&key!=='received_transaction_id'||x.amount>0).map(x=>[x.id,x.label]);
    if(key==='transaction_ids')opts=choices.payments.map(x=>[x.id,x.label]);
    if(key==='accounts')opts=choices.accounts.map(x=>[x,x]);
    if(opts){const multi=f.type==='lines',current=Array.isArray(v)?v:[v];if(v&&!multi&&!opts.some(x=>x[0]===v))opts.push([v,'Saved selection (no longer available)']);return `<label>${esc(f.label.replace(' IDs, one per line','s').replace(' ID',''))}<select ${attrs} ${multi?'multiple size="6"':''}>${multi?'':`<option value="">Choose…</option>`}${opts.map(([k,l])=>`<option value="${esc(k)}" ${current.includes(k)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
    if(f.type==='checkbox')return `<label class="ws-check"><input type="checkbox" ${attrs} ${v?'checked':''}>${esc(f.label)}</label>`;
    if(f.type==='select'||f.type==='category'){const opts=f.type==='category'?[['','All expenses'],...WS.categories.filter(c=>c.kind==='expense').map(c=>[c.id,c.name])]:(f.options||[]).map(x=>[x,x]);return `<label>${esc(f.label)}<select ${attrs}>${opts.map(([k,l])=>`<option value="${esc(k)}" ${k===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
    if(['textarea','lines'].includes(f.type))return `<label>${esc(f.label)}<textarea rows="3" ${attrs}>${esc(Array.isArray(v)?v.join('\n'):v)}</textarea></label>`;
    return `<label>${esc(f.label)}<input type="${f.type==='number'?'number':f.type==='date'?'date':'text'}" ${attrs} ${f.type==='number'?'step="any"':''} value="${esc(v)}"></label>`;
  }).join('');
  const dlg=$('#dlg'),form=$('#dlgForm');form.innerHTML=`<div class="ws-panel"><div class="card-head"><h2>${ident?'Edit':'Add'} ${esc(kind)}</h2><button type="button" class="icon-btn" id="wsCancel" aria-label="Close">×</button></div><div class="ws-forms">${fields}</div>${kind==='coverage'?wsScope('Adjusted returns are withheld until external flows are complete for the selected dates. Confirm only after checking all deposits and withdrawals.'):kind==='property'?wsScope('This planning record does not add the property to net worth.'):kind==='refund'?wsScope('Links an existing bank credit to purchase evidence. It creates no new payment and does not change spending categories.'):''}<div class="ws-form-actions"><button type="submit" class="btn">Save</button><button type="button" class="btn ghost" id="wsCancel2">Cancel</button></div><div id="wsFormError" class="ws-live-region" role="status"></div></div>`;
  form.method='dialog';form.onsubmit=async e=>{e.preventDefault();const data={};for(const [key,f] of Object.entries(schema)){const input=form.elements.namedItem(key);data[key]=input.multiple?Array.from(input.selectedOptions,x=>x.value):f.type==='checkbox'?input.checked:f.type==='number'?(input.value===''?null:Number(input.value)):input.value;}
    const b=form.querySelector('[type=submit]');b.disabled=true;try{await wsPost('record',{kind,id:ident||undefined,data});dlg.close();toast('Saved locally');wsRefresh();}catch(err){$('#wsFormError').textContent=err.message;}finally{b.disabled=false;}};
  if(kind==='refund')form.elements.document_id.onchange=()=>{const options=choices.products.filter(x=>x.document_id===form.elements.document_id.value);form.elements.item_id.innerHTML='<option value="">Whole invoice</option>'+options.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('');};
  $('#wsCancel').onclick=$('#wsCancel2').onclick=()=>dlg.close();if(!dlg.open)dlg.showModal();
}
async function wsRefresh(){if(view==='review')reviewPage();else if(view==='explore')workspacePage();await wsLoadSummary();}
async function wsLoadSummary(){try{WS.summary=await wsGet('summary');let nav=$('#nav a[href="#review"]');if(nav){let tag=$('.ws-badge',nav);if(!tag){tag=document.createElement('span');tag.className='ws-badge';nav.append(tag);}tag.textContent=WS.summary.review_count||'';tag.hidden=!WS.summary.review_count;}
  if(WS.notifications&&'Notification'in window&&Notification.permission==='granted'){const seen=new Set(store.get('ws.notified',[]));for(const e of WS.summary.events||[]){if(seen.has(e.id))continue;new Notification('Wealth',{body:e.title,tag:e.id});seen.add(e.id);}store.set('ws.notified',[...seen].slice(-500));}
}catch{}}
async function reviewPage(){
 const gen=++WS.generation;$('#view').innerHTML=`<div class="stack-y"><div class="ws-header"><div><p class="muted">Imports, purchase evidence and anything worth a check.</p></div><div class="controls">${wsButton('Scan intake folder','scan')}${wsButton('Import files','import')}</div></div><div id="wsReview">${skeleton()}</div></div>`;wsBind();
 try{const d=await wsGet('review');if(gen!==WS.generation||view!=='review')return;WS.data=d;
  $('#wsReview').innerHTML=`<div class="ws-filter"><div class="seg tabs ws-tabs">${[['all','All'],['intake','Imports'],['receipt','Invoices'],['payment','Payments'],['signal','Signals']].map(([k,l])=>`<button type="button" aria-pressed="${WS.filter===k}" data-ws-filter="${k}">${l}${k==='all'?` <span class="tab-n">${d.total}</span>`:d.counts[k]?` <span class="tab-n">${d.counts[k]}</span>`:''}</button>`).join('')}</div><input type="search" id="wsReviewSearch" placeholder="Search review items" aria-label="Search review items" value="${esc(WS.q)}"></div>${intCard('To review','<div id="wsReviewRows" class="ws-list"></div>')}${intCard('Local document intake',`<p class="small">Put files in <b>import-inbox</b> inside the dashboard folder. They are checked every 45 seconds and prepared here.</p><p class="muted small">Original evidence is retained. Imports use your existing importer and Undo.</p><div class="controls">${wsButton('Open intake folder','open-folder')}${wsButton('Invoices & refunds','receipts')}${wsButton('Document coverage','documents')}</div>`)}`;
  const draw=()=>{const rows=d.tasks.filter(t=>(WS.filter==='all'||t.kind===WS.filter)&&(t.title+' '+t.detail).toLowerCase().includes(WS.q.toLowerCase()));$('#wsReviewRows').innerHTML=rows.length?rows.map(t=>`<div class="ws-row"><div><h3>${esc(t.title)}</h3><span class="muted small">${esc(t.detail)}</span></div><div class="controls">${wsButton(t.kind==='intake'?'Import':'Open','task',t.id)}${wsButton('Later','dismiss',t.id)}</div></div>`).join(''):wsEmpty('Nothing needs your attention in this selection.');wsBind($('#wsReviewRows'));};
  $$('[data-ws-filter]').forEach(b=>b.onclick=()=>{WS.filter=b.dataset.wsFilter;reviewPage();});$('#wsReviewSearch').oninput=e=>{WS.q=e.target.value;draw();};draw();wsBind();
 }catch(e){if(gen===WS.generation)$('#wsReview').innerHTML=intCard('Review unavailable',wsEmpty(e.message));}
}
async function workspacePage(){
 if(!WS_TABS.some(t=>t[0]===WS.tab))WS.tab='cashflow';const tab=WS.tab,gen=++WS.generation;
 $('#view').innerHTML=`<div class="stack-y"><div class="int-nav ws-nav" aria-label="Connected workflows">${WS_TABS.map(([k,l])=>`<button type="button" data-ws-tab="${k}" class="${tab===k?'active':''}" aria-current="${tab===k?'page':'false'}">${l}</button>`).join('')}</div><div id="wsBody">${skeleton()}</div></div>`;wsBind();
 try{const q=tab==='performance'?{account:WS.account,...WS.period}:tab==='cashflow'?{month:WS.month}:{};const d=await wsGet(tab,q);if(gen!==WS.generation||view!=='explore'||tab!==WS.tab)return;WS.data=d;
  ({cashflow:wsCashflow,performance:wsPerformance,research:wsResearch,planning:wsPlanning,documents:wsDocuments,connections:wsConnections,backups:wsBackups})[tab](d);wsBind();
 }catch(e){if(gen===WS.generation)$('#wsBody').innerHTML=intCard('This view is unavailable',wsEmpty(e.message)+wsButton('Try again','reload'));}
}
function wsCashflow(d){const f=d.forecast,a=d.analysis;$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>What is coming up</h2><p class="muted small">Known commitments and recurring patterns, with the evidence behind them.</p></div>${wsAdd('bill','Add a commitment')}</div><div class="int-metrics">${intMetric('In 30 days',eur(f.checkpoints['30']))}${intMetric('In 60 days',eur(f.checkpoints['60']))}${intMetric('In 90 days',eur(f.checkpoints['90']))}${intMetric('Lowest scheduled balance',eur(f.lowest_eur))}</div>${intCard('Cash-flow outlook','<div id="wsForecastChart"></div>'+wsScope(f.basis)+`<details><summary>Opening balance & assumptions</summary><form id="wsOpening" class="controls"><input name="opening" type="number" step="0.01" placeholder="Optional confirmed opening balance €" aria-label="Opening balance" value="${f.opening_eur??''}"><button class="btn ghost sm">Set opening balance</button></form>${wsScope(f.assumptions)}</details>`)}
 ${intCard('Scheduled payments',wsTable([['date','Date',v=>`<span class="nowrap">${fdate(v)}</span>`],['name','Payment'],['amount_eur','Amount',v=>eur(v,2)],['source','Basis',v=>`<span class="muted small">${esc(v||'')}</span>`]],f.events,40))}${intCard('Recurring patterns',wsTable([['name','Merchant'],['amount_eur','Latest',v=>eur(v,2)],['frequency','Frequency'],['annual_eur','Annualised',v=>eur(v)],['change_eur','Change',v=>sgn(v,2)],['evidence_ids','Evidence',(v,r)=>wsButton('Open payment','payment',v.at(-1))]],d.recurring.filter(r=>r.active),30), 'Detected patterns are suggestions; annual totals assume the latest payment continues.')}
 ${intCard('What changed',`<div class="controls"><label class="small">Month <input id="wsMonth" type="month" value="${esc(a.month)}"></label>${wsButton('Payments','spending')}</div>${wsTable([['name','Category'],['previous_eur','Previous month',v=>eur(v)],['current_eur','Selected month',v=>eur(v)],['change_eur','Change',v=>sgn(v)]],a.categories,15)}<details><summary>Merchant changes & supporting payments</summary>${wsTable([['name','Merchant'],['change_eur','Change',v=>sgn(v)],['transaction_ids','Evidence',v=>v.length?wsButton('Open','payment',v[0]):'—']],a.merchants,30)}</details>`,a.scope)}
 <div class="grid g3">${wsRecordCard('bill','Commitments',d.bills)}${wsRecordCard('claim','Reimbursements',d.claims)}${intCard('Trips & projects',wsTable([['name','Project'],['expenses_eur','Out',v=>eur(v)],['incoming_eur','Back',v=>eur(v)],['remaining_budget_eur','Budget remaining',v=>eur(v)],['id','',v=>wsButton('Edit','edit',v,'data-ws-kind="project"')]],d.projects)+`<div class="controls">${wsAdd('project','Add trip or project')}</div>`)}</div></div>`;
 wsChart('wsForecastChart','Scheduled balance',f.curve,'balance_eur');
 $('#wsOpening').onsubmit=async e=>{e.preventDefault();try{await wsPost('opening',{opening_eur:e.target.elements.opening.value===''?null:Number(e.target.elements.opening.value)});workspacePage();}catch(err){toast(err.message);}};$('#wsMonth').onchange=e=>{WS.month=e.target.value;workspacePage();};
}
function wsPerformance(d){WS.account=d.account;store.set('ws.account',d.account);const p=d.performance;$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Your actual investment record</h2><p class="muted small">Cash flows and execution evidence remain separate from today's holdings.</p></div><select id="wsAccount" aria-label="Investment account">${d.accounts.map(a=>`<option ${a===d.account?'selected':''}>${esc(a)}</option>`).join('')}</select></div><form id="wsPeriod" class="controls"><label class="small">From <input name="from" type="date" value="${esc(WS.period.from)}"></label><label class="small">To <input name="to" type="date" value="${esc(WS.period.to)}"></label><button class="btn ghost sm">Apply period</button><button type="button" class="linkish small" id="wsAllPeriod">All recorded history</button></form>${wsScope(p.start?`Recorded endpoints: ${p.start} to ${p.end}`:'No recorded endpoints in this period.')}<div class="int-metrics">${intMetric('Time-weighted return',intPct(p.twr_pct))}${intMetric('Personal annualised return',intPct(p.money_weighted.value_pct))}${intMetric('Profit after external flows',eur(p.profit_eur))}${intMetric('Net external contributions',eur(p.net_contributions_eur))}</div>
 ${intCard('Recorded account value','<div id="wsAccountValue"></div>')}${intCard('Cash-flow-adjusted history','<div id="wsAdjusted"></div>'+wsScope(p.reason||p.scope)+`<details><summary>Coverage & calculation evidence</summary>${wsScope(p.scope)}<p class="small">Modified Dietz approximation: ${intPct(p.modified_dietz_pct)}</p>${wsScope(p.money_weighted.reason)}<div class="controls">${wsButton('Review flow completeness','coverage',d.account)}${wsAdd('flow','Add external flow')}${wsAdd('valuation','Add recorded valuation')}</div>${wsTable([['date','Date'],['amount_eur','External flow',v=>eur(v,2)],['source','Source']],d.flows)}${wsRecordCard('flow','Manually recorded external flows',d.flow_records||[])}</details>`)}
 ${intCard('Imported gains & remaining lots',wsTable([['name','Investment'],['remaining_units','Remaining units',v=>intNum(v,4)],['remaining_cost_eur','FIFO cost',v=>eur(v)],['realized_eur','Realised',v=>sgn(v)],['unrealized_eur','Unrealised',v=>sgn(v)],['complete','Coverage',(v,r)=>v?'Reconciled':esc(r.issues.join(' '))]],d.lots),d.scope)}
 <div class="grid g2">${intCard('Income, fees & taxes',wsTable([['type','Recorded type'],['amount','Amount',v=>eur(v,2)]],Object.entries(d.totals).map(([type,amount])=>({type:type.replaceAll('_',' '),amount}))), 'Only explicitly available execution amounts; a missing total is not zero.')}${intCard('Broker ledger imports',`<p class="small">Retain complete execution history—including sold positions—without replacing your current holdings.</p><div class="controls">${wsButton('Import ledger CSV','import')}<a class="btn ghost sm" href="/api/workspace/export?what=ledger-template">Download CSV template</a><a class="btn ghost sm" href="/api/workspace/export?what=ledger&account=${encodeURIComponent(d.account)}">Export ledger</a></div>`)}</div>
 ${intCard('Execution evidence',wsTable([['date','Date'],['name','Instrument'],['type','Type'],['units','Units',v=>intNum(v,4)],['amount_eur','EUR cash',v=>eur(v,2)],['source_id','Original',v=>v?`<a href="/api/receipts/source?id=${encodeURIComponent(v)}" target="_blank" rel="noopener">Evidence</a>`:'Held-position import']],d.events,100))}
 <details class="card"><summary>Bond yield & cash-flow calculator</summary><form id="wsBond" class="ws-forms">${[['face_eur','Face value €'],['price_eur','Verified cash price €'],['coupon_pct','Annual coupon %'],['accrued_eur','Accrued interest €'],['fee_eur','Fees €']].map(([k,l])=>`<label>${l}<input name="${k}" type="number" min="0" step="any" value="${['accrued_eur','fee_eur'].includes(k)?0:''}" required></label>`).join('')}<label>Maturity<input name="maturity" type="date" required></label><label>Coupons per year<select name="frequency"><option>1</option><option>2</option><option>4</option></select></label><button class="btn">Calculate</button></form><div id="wsBondResult" class="ws-output"></div></details></div>`;
 $('#wsPeriod').onsubmit=e=>{e.preventDefault();WS.period=Object.fromEntries(new FormData(e.target));store.set('ws.period',WS.period);workspacePage();};$('#wsAllPeriod').onclick=()=>{WS.period={from:'',to:''};store.set('ws.period',WS.period);workspacePage();};wsChart('wsAccountValue','Recorded account value',d.valuations,'value');wsChart('wsAdjusted','Adjusted return index',p.curve,'index','index');$('#wsAccount').onchange=e=>{WS.account=e.target.value;workspacePage();};
 $('#wsBond').onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));for(const k of Object.keys(b))if(k!=='maturity')b[k]=Number(b[k]);const r=await wsPost('bond',b);$('#wsBondResult').innerHTML=`<div class="int-metrics">${intMetric('Yield to maturity',intPct(r.yield_to_maturity_pct))}${intMetric('Modified duration',intNum(r.modified_duration_years,2)+' years')}</div>${wsTable([['date','Date'],['amount_eur','Cash flow',v=>eur(v,2)]],r.cashflows)}${wsScope(r.scope)}`;}catch(err){$('#wsBondResult').textContent=err.message;}};
}
function wsResearch(d){$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Your research desk</h2><p class="muted small">Company evidence, public sources and the reasoning behind decisions.</p></div>${wsButton('Investment workspace','investments')}</div>${intCard('Company comparisons',`<div class="ws-filter"><input id="wsScreenQ" type="search" placeholder="Company or ticker" aria-label="Company or ticker"><input id="wsScreenPE" type="number" min="0" step="any" placeholder="Maximum P/E" aria-label="Maximum P/E"><input id="wsScreenGrowth" type="number" step="any" placeholder="Minimum revenue growth %" aria-label="Minimum revenue growth"><label class="small ws-check"><input id="wsScreenProfitable" type="checkbox"> Profitable only</label></div><div id="wsScreenRows"></div>`,d.scope)}
 ${wsPublicPanel()}${wsRecordCard('decision','Investment decisions',d.decisions)}${wsRecordCard('note','Facts, assumptions & questions',d.notes)}${intCard('Saved research questions',d.prompts.map(r=>`<div class="ws-row"><div><h3>${esc(r.name)}</h3><p class="muted small">${esc(r.text)}</p></div>${wsButton('Ask','prompt',r.id)}</div>`).join('')+`<div class="controls">${wsAdd('prompt','Save a question')}</div>`)}<details class="card"><summary>Peer groups from available classifications</summary>${wsTable([['name','Industry'],['symbols','Companies',v=>esc(v.join(', '))]],Object.entries(d.peers).map(([name,symbols])=>({name,symbols})))}</details>${intCard('Public research already retrieved',wsTable([['name','Source'],['query','Query'],['retrieved_at','Retrieved',v=>intDate(v)],['rows','Records',v=>v.length]],d.public_queries))}<details class="card"><summary>Follow official announcements & research feeds</summary><p class="muted small">Save a public RSS or Atom feed. New items appear in local activity after a refresh.</p><div id="wsFeeds"></div><div class="controls">${wsAdd('feed','Add public feed')}${wsButton('Refresh feeds','feed-refresh')}</div></details></div>`;
 const draw=()=>{const q=$('#wsScreenQ').value.toLowerCase(),pe=$('#wsScreenPE').value,growth=$('#wsScreenGrowth').value,profitable=$('#wsScreenProfitable').checked;const rows=d.opportunities.filter(r=>{const f=r.fundamentals||{};return(r.name+' '+r.symbol).toLowerCase().includes(q)&&(!pe||(f.trailing_pe!=null&&f.trailing_pe>0&&f.trailing_pe<=+pe))&&(!growth||(f.revenue_growth!=null&&f.revenue_growth*100>=+growth))&&(!profitable||(f.profit_margin!=null&&f.profit_margin>0));});$('#wsScreenRows').innerHTML=wsTable([['name','Company',(v,r)=>`<button class="linkish" data-ws-company="${esc(r.symbol)}">${esc(v)}</button>`],['score','Score',v=>intScore(v)],['fundamentals','P/E',v=>intRatio(v?.trailing_pe)],['fundamentals','Revenue growth',v=>intPct(v?.revenue_growth==null?null:v.revenue_growth*100)],['status','Coverage']],rows);wsBind($('#wsScreenRows'));};['wsScreenQ','wsScreenPE','wsScreenGrowth','wsScreenProfitable'].forEach(id=>$('#'+id).oninput=draw);draw();wsBindPublic();wsGet('records',{kind:'feed'}).then(r=>{if($('#wsFeeds')){$('#wsFeeds').innerHTML=wsRecordRows('feed',r.items);wsBind($('#wsFeeds'));}});
}
function wsPublicPanel(){return intCard('Public data & research',`<form id="wsPublicForm"><div class="ws-forms"><label>Source<select name="source"><option value="afmshort">AFM · disclosed short positions</option><option value="afminsider">AFM · management transactions</option><option value="bis">BIS · real exchange-rate index</option><option value="oecd">OECD · leading indicator</option><option value="fred">FRED · US economic series</option><option value="fda">openFDA · applications & submissions</option><option value="krakenhistory">Kraken · daily crypto history</option><option value="ecb">ECB · rates, FX & inflation</option><option value="worldbank">World Bank · annual inflation</option><option value="eurostat">Eurostat · monthly inflation</option><option value="cbs">CBS · Dutch price statistics</option><option value="openfigi">OpenFIGI · security identifiers</option><option value="gleif">GLEIF · legal company identity</option><option value="gdelt">GDELT · worldwide news</option><option value="trials">ClinicalTrials.gov · studies</option><option value="usaspending">USAspending · government awards</option><option value="ted">TED · European procurement</option><option value="kraken">Kraken · public crypto quotes</option></select></label><label>Public company, identifier or country code<input name="term" placeholder="e.g. Apple, US0378331005, NL or XBTEUR"></label></div><div class="ws-form-actions"><button class="btn ghost">Retrieve public data</button><span id="wsPublicStatus" class="muted small" role="status"></span></div></form><div id="wsPublicResult" class="ws-output"></div>`, 'Public queries contain only the term you enter. Personal payments and bank details are not included. Results are cached locally.');}
function wsBindPublic(){const form=$('#wsPublicForm');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;$('#wsPublicStatus').textContent='Retrieving public evidence…';try{const r=await wsPost('public',Object.fromEntries(new FormData(form)));const rows=r.rows||[];const keys=[...new Set(rows.flatMap(x=>Object.keys(x)))].filter(k=>!['payload','source_url'].includes(k)).slice(0,8);$('#wsPublicResult').innerHTML=`<div class="card-head"><h3>${esc(r.name)}</h3>${intURL(r.documentation,'Source documentation')}</div>${wsScope('Retrieved '+intDate(r.retrieved_at)+(r.stale?' · cached / stale':''))}${r.warning?wsScope(r.warning):''}${r.series?.length?'<div id="wsPublicChart"></div>':''}${wsTable(keys.map(k=>[k,k.replaceAll('_',' '),(v,row)=>k==='title'&&row.source_url?intURL(row.source_url,v):esc(typeof v==='object'?JSON.stringify(v):v??'—')]),rows,50)}${r.truncated?wsScope(`${r.total_rows} matching records; the response retains a bounded selection.`):''}${wsScope(r.scope)}`;if(r.series?.length)wsChart('wsPublicChart',r.name,r.series,'value',r.source==='worldbank'||r.source==='eurostat'?'%':'');$('#wsPublicStatus').textContent=r.cached?'Cached evidence':'Retrieved';}catch(err){$('#wsPublicStatus').textContent=err.message;}finally{button.disabled=false;}};}
function wsPlanning(d){$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Plans with their evidence</h2><p class="muted small">Keep commitments, goals and assumptions connected.</p></div>${wsAdd('goal','Add a goal')}</div>${intCard('Goals',wsTable([['name','Goal'],['saved_eur','Reserved',v=>eur(v)],['target_eur','Target',v=>eur(v)],['due','By'],['monthly_required_eur','Required each month',v=>eur(v)],['progress_pct','Progress',v=>intPct(v)],['id','',v=>v?wsButton('Edit','edit',v,'data-ws-kind="goal"'):'Existing Plan page']],[...d.goals,...d.existing_goals]),'No investment growth is assumed in the required monthly saving calculation.')}
 <div class="grid g2">${wsRecordCard('claim','Reimbursements',d.claims)}${wsRecordCard('policy','Insurance & warranties',d.policies)}</div>${wsRecordCard('property','Property evidence',d.properties,d.scope)}${wsRecordCard('project','Trips & projects',d.projects)}

 <details class="card"><summary>Combined stress scenario</summary><form id="wsStress" class="ws-forms">${[['equity_pct','Shares & funds change %',-20],['bonds_pct','Bond price change %',-5],['crypto_pct','Crypto change %',-40],['income_loss_months','Months requiring an expense reserve',3],['monthly_expense_eur','Monthly expense reserve €',0]].map(([k,l,v])=>`<label>${l}<input name="${k}" type="number" step="any" value="${v}" required></label>`).join('')}<button class="btn ghost">Calculate scenario</button></form><div id="wsStressResult" class="ws-output"></div></details>
 <details class="card"><summary>Deposits by legal institution</summary><p class="muted small">Group accounts using verified institutional identity and protection terms.</p><div id="wsInstitutions"></div>${wsAdd('institution','Add verified institution')}</details></div>`;

 $('#wsStress').onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));Object.keys(b).forEach(k=>b[k]=Number(b[k]));const r=await wsPost('stress',b);$('#wsStressResult').innerHTML=`<div class="int-metrics">${intMetric('Net-worth impact',sgn(r.net_worth_impact_eur))}${intMetric('Expense reserve',eur(r.expense_reserve_eur))}</div>${wsTable([['name','Investment'],['before_eur','Current',v=>eur(v)],['after_eur','Scenario',v=>eur(v)],['change_eur','Impact',v=>sgn(v)]],r.positions,30)}${wsScope(r.scope)}`;}catch(err){toast(err.message);}};
 wsGet('institutions').then(r=>{if($('#wsInstitutions')){$('#wsInstitutions').innerHTML=wsTable([['name','Institution'],['total_eur','Total',v=>eur(v)],['limit_eur','Verified limit',v=>eur(v)],['above_limit_eur','Above stated limit',v=>eur(v)],['id','',v=>wsButton('Edit','edit',v,'data-ws-kind="institution"')]],r.items)+wsScope(r.scope);wsBind($('#wsInstitutions'));}});
}
function wsDocuments(d){$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Your evidence library</h2><p class="muted small">Search originals, product lines and locally extracted document text.</p></div><div class="controls">${wsButton('Index originals','index')}${wsButton('Invoices & payment links','receipts')}</div></div>${intCard('Search documents',`<input id="wsDocSearch" type="search" placeholder="Supplier, product, invoice number or text" aria-label="Search evidence"><div id="wsDocRows"></div>`)}
 ${intCard('Refunds & returns',wsTable([['name','Return'],['amount_eur','Bank refund allocation',v=>eur(v,2)],['transaction_id','Payment',v=>wsButton('Open','payment',v)],['id','',v=>wsButton('Edit','edit',v,'data-ws-kind="refund"')]],d.refunds)+`<div class="controls">${wsAdd('refund','Link an existing refund')}</div>`, 'Refunds remain existing bank credits. A link traces purchase evidence without creating another transaction.')}
 ${intCard('Import coverage',wsTable([['name','Payment account'],['from','First record'],['to','Last record'],['transactions','Records'],['months_without_records','Months to check',v=>esc(v.join(', ')||'None within the recorded range')]],d.coverage.accounts), 'A month without transactions is a gap to check; it does not prove a statement is missing.')}
 ${wsRecordCard('rule','Document layout notes',d.layouts,'Saved recognition notes help you retain recurring supplier corrections. They do not bypass import validation.')}
 <details class="card"><summary>Compare two document versions</summary><form id="wsCompare" class="ws-forms">${['first','second'].map(k=>`<label>${k==='first'?'Earlier':'Later'} document<select name="${k}">${d.indexed.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label>`).join('')}<button class="btn ghost">Compare text</button></form><div id="wsCompareResult" class="ws-output"></div></details></div>`;
 const draw=()=>{const q=$('#wsDocSearch').value.toLowerCase();const indexed=d.indexed.filter(r=>(r.name+' '+r.text).toLowerCase().includes(q));const invoices=d.invoices.filter(r=>(r.supplier+' '+r.invoice_number+' '+r.order_number+' '+r.items.map(i=>i.description).join(' ')).toLowerCase().includes(q));$('#wsDocRows').innerHTML=wsTable([['name','Document'],['status','Text extraction'],['source_id','Original',v=>`<a href="/api/receipts/source?id=${encodeURIComponent(v)}" target="_blank" rel="noopener">Open original</a>`],['id','Search text',v=>wsButton('Read text','document',v)]],indexed)+`<details><summary>Matching invoices & product lines (${invoices.length})</summary>${invoices.map(r=>`<div class="ws-row"><div><h3>${esc(r.supplier||'Invoice')} · ${receiptMoney(r.total,r.currency)}</h3><div class="muted small">${esc(r.invoice_number||r.order_number||'')} · ${esc(r.date)}</div><p class="small">${r.items.map(i=>esc(i.description)).join(' · ')}</p>${r.links?.length?`<span class="muted small">${r.links.length} payment link${r.links.length===1?'':'s'}</span>`:'<span class="muted small">Awaiting payment link</span>'}</div>${wsButton('Payment links','receipts')}</div>`).join('')||wsEmpty('No matching invoices.')}</details>`;wsBind($('#wsDocRows'));};$('#wsDocSearch').oninput=draw;draw();
 $('#wsCompare').onsubmit=async e=>{e.preventDefault();try{const r=await wsPost('compare',Object.fromEntries(new FormData(e.target)));$('#wsCompareResult').innerHTML=`<pre class="ws-document">${esc(r.changes.join('\n')||'No text differences found.')}</pre>${wsScope(r.scope)}`;}catch(err){$('#wsCompareResult').textContent=err.message;}};
}
function wsConnections(d){const live=d.items.filter(r=>r.status!=='Not connected'),optional=d.items.filter(r=>r.status==='Not connected');const render=rows=>rows.map(r=>`<div class="ws-connection"><div><b>${esc(r.name)}</b><p>${esc(r.supplies)}</p></div><div><span class="small">${esc(r.status)}</span><p>${esc(r.access)}${r.last_retrieved?' · '+intDate(r.last_retrieved):''}</p></div>${intURL(r.url,'Details')}</div>`).join('');$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Connections & coverage</h2><p class="muted small">Know what is available, what is connected and where the data came from.</p></div>${wsButton('Existing provider settings','settings')}</div>${intCard('Available sources',render(live))}${intCard('Optional connections',`<details><summary>Explore ${optional.length} additional services</summary>${render(optional)}</details>`,d.scope)}${intCard('Investment refresh jobs',wsTable([['name','Job'],['status','Status'],['cursor','Progress'],['finished_at','Last completed',v=>v?intDate(v):'Not yet']],d.investment.jobs)+`<details><summary>Unavailable sources (${d.investment.errors.length})</summary>${d.investment.errors.map(e=>`<p class="muted small">${esc(e)}</p>`).join('')}</details>`)}${wsPublicPanel()}<details class="card"><summary>Desktop alerts</summary><p class="muted small">Optional browser notifications while the dashboard is open.</p>${wsButton(WS.notifications?'Disable desktop alerts':'Enable desktop alerts','notifications')}</details></div>`;wsBindPublic();}
function wsBackups(d){$('#wsBody').innerHTML=`<div class="stack-y"><div class="ws-header"><div><h2>Backups & recovery</h2><p class="muted small">Financial records, original evidence and both local databases together.</p></div>${wsButton('Create complete backup','backup')}</div>${intCard('Encrypted backups',wsTable([['created','Created',v=>intDate(v)],['files','Files'],['bytes','Original size',v=>intNum(v/1024/1024,1)+' MB'],['mode','Unlock method'],['name','Verify restoration',v=>wsButton('Verify separate copy','restore',v)]],d.items), 'Local-owner backups require the owner key on this computer. Password-protected backups can be portable; passwords are not stored.')}
 <details class="card"><summary>Create a portable password-protected backup</summary><form id="wsPortable" class="ws-forms"><label>Backup password (at least 10 characters)<input name="password" type="password" minlength="10" autocomplete="new-password" required></label><button class="btn ghost">Create encrypted backup</button></form><div id="wsPortableResult" class="ws-live-region" role="status"></div></details>
 ${intCard('Recent workflow changes',wsTable([['created','When',v=>intDate(v)],['action','Change'],['kind','Record type'],['record_id','Reference']],d.audit), 'Local audit history for planning, evidence links and workflow records. Existing financial imports retain their existing Undo workflow.')}${intCard('Take your data with you',`<div class="controls"><a class="btn ghost sm" href="/api/workspace/export?what=xlsx">Excel workbook</a><a class="btn ghost sm" href="/api/workspace/export?what=calendar">Upcoming dates for calendar</a><a class="btn ghost sm" href="/api/workspace/export?what=demo">Fresh fictional demo</a>${wsButton('Print / save as PDF','print')}</div>`,'The demo is generated from application source and invented data. Your records, credentials, documents and Git history are excluded.')}${wsScope('Weekly complete backups and local briefings run while the dashboard is running. Last backup: '+(d.maintenance.backup_at?intDate(d.maintenance.backup_at):'awaiting first run')+'.')}<div id="wsRestoreResult"></div></div>`;
 $('#wsPortable').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await wsPost('backup',{password:e.target.elements.password.value});e.target.reset();toast('Encrypted backup created');workspacePage();}catch(err){$('#wsPortableResult').textContent=err.message;}finally{b.disabled=false;}};
}
function wsBind(root=$('#view')){if(!root)return;
 $$('[data-ws-tab]',root).forEach(b=>b.onclick=()=>wsNavigate(b.dataset.wsTab));
 $$('[data-ws-company]',root).forEach(b=>b.onclick=()=>intNavigate('research',b.dataset.wsCompany));
 $$('[data-ws-action]',root).forEach(b=>b.onclick=async()=>{const a=b.dataset.wsAction,id=b.dataset.wsId;try{
  if(a==='add')return wsEdit(id);
  if(a==='edit')return wsEdit(b.dataset.wsKind,id);
  if(a==='delete'){if(!confirmTwice('ws-'+id,'Click Remove again to remove this saved workflow record.'))return;await wsPost('record',{kind:b.dataset.wsKind,id,delete:true});return wsRefresh();}
  if(a==='coverage')return wsEdit('coverage',id,{account:id});
  if(a==='payment')return wsOpenPayment(id);
  if(a==='receipts')return wsOpenReceipt();
  if(a==='documents')return wsNavigate('documents');
  if(a==='settings'){location.hash='settings';return;}
  if(a==='spending'){location.hash='spending';return;}
  if(a==='investments'){intNavigate('portfolio');return;}
  if(a==='import'){location.hash='import';return;}
  if(a==='reload')return wsRefresh();
  if(a==='print')return window.print();
  if(a==='task'){const t=WS.data.tasks.find(t=>t.id===id);if(!t)return;if(t.kind==='intake'){b.disabled=true;b.textContent='Importing…';const r=await wsPost('intake',{id:t.target});toast(r.summary?.slice(0,150)||'Imported');await load();return wsRefresh();}if(t.kind==='receipt')return wsOpenReceipt();if(t.kind==='payment')return wsOpenPayment(t.target);if(t.kind==='signal'){intNavigate('alerts');return;}return wsEdit(t.kind,t.target);}
  if(a==='prompt'){const r=WS.data.prompts.find(r=>r.id===id);if(r)openChat({text:r.text,ctx:{title:r.name,text:'Use the dashboard tools for calculations and show evidence dates.'}});return;}
  if(a==='document'){const r=WS.data.indexed.find(r=>r.id===id);if(!r)return;const dlg=$('#dlg');$('#dlgForm').innerHTML=`<div class="ws-panel"><div class="card-head"><h2>${esc(r.name)}</h2><button class="btn ghost sm" value="close">Close</button></div><pre class="ws-document">${esc(r.text||r.status)}</pre><p><a href="/api/receipts/source?id=${encodeURIComponent(r.source_id)}" target="_blank" rel="noopener">Open original evidence</a></p></div>`;$('#dlgForm').onsubmit=null;dlg.showModal();return;}
  if(a==='notifications'){if(!('Notification'in window))throw Error('Desktop notifications are unavailable in this browser.');if(WS.notifications){WS.notifications=false;}else{const p=await Notification.requestPermission();WS.notifications=p==='granted';}store.set('ws.notifications',WS.notifications);return wsRefresh();}
  if(a==='open-folder'){await wsPost('open-folder');toast('Intake folder opened');return;}
  b.disabled=true;
  if(a==='restore'){const item=WS.data.items.find(r=>r.name===id);let password;if(item?.mode==='password'){password=prompt('Password for this encrypted backup');if(password===null)return;}const r=await wsPost('restore-preview',{name:id,password});$('#wsRestoreResult').innerHTML=intCard('Restore verified',`<p class="small">${r.files} files verified in <b>${esc(r.folder)}</b>.</p>${wsScope(r.scope)}<details><summary>Verified contents</summary>${wsTable([['name','File'],['bytes','Bytes']],r.manifest,100)}</details>`);toast('Separate restore copy verified');return;}
  const r=await wsPost(a,a==='dismiss'?{id}:{});toast(a==='backup'?'Complete encrypted backup created':a==='scan'?`${r.added} new files prepared`:a==='index'?`${r.indexed} originals indexed`:'Saved');return wsRefresh();
 }catch(e){toast(e.message);}finally{if(b.isConnected){b.disabled=false;if(a==='task')b.textContent='Import';}}});
}
const wsOriginalRenderView=renderView;renderView=function(){if(view==='review')return reviewPage();if(view==='explore')return workspacePage();return wsOriginalRenderView();};
TITLES.review='Review';TITLES.explore='Explore';
$('#nav a[href="#import"]').insertAdjacentHTML('beforebegin','<a href="#review"><svg viewBox="0 0 24 24"><path d="M4 4h16v16H4zM8 9l2 2 5-5M8 16h8"/></svg>Review</a><a href="#explore"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M15 9l-2 4-4 2 2-4z"/></svg>Explore</a>');
const wsOriginalOverview=overview;overview=function(){wsOriginalOverview();const gen=WS.generation;wsGet('summary').then(r=>{if(view!=='overview'||$('#wsToday'))return;const target=$('#view>.stack-y')||$('#view');target.insertAdjacentHTML('beforeend',`<section class="card ws-overview-card" id="wsToday"><div class="card-head"><h2>Ready when you are</h2><a class="linkish small" href="#review">${r.review_count} to review</a></div>${r.upcoming.length?wsTable([['next_date','Coming up'],['name','Payment'],['amount_eur','Expected',v=>eur(v,2)]],r.upcoming):wsEmpty('Recurring commitments appear here once enough payment history is available.')}<div class="controls">${wsButton('Cash-flow outlook','today-cash')}${wsButton('Connections','today-connections')}<a class="linkish small" href="/api/workspace/export?what=digest">Download current briefing</a></div></section>`);$$('[data-ws-action="today-cash"]').forEach(b=>b.onclick=()=>wsNavigate('cashflow'));$$('[data-ws-action="today-connections"]').forEach(b=>b.onclick=()=>wsNavigate('connections'));}).catch(()=>{});};
// Settings links to backups, documents and connections live in its Data group (app.js).
const wsOriginalIntNav=intNav;intNav=function(){return wsOriginalIntNav()+`<div class="controls" style="margin-top:8px"><button type="button" class="linkish small" onclick="wsNavigate('performance')">Actual account performance</button><button type="button" class="linkish small" onclick="wsNavigate('research')">Research desk</button></div>`;};
const wsOriginalSearchIndex=searchIndex;searchIndex=function(){return [...wsOriginalSearchIndex(),...WS_TABS.map(([tab,title])=>({type:'Workspace',name:title,base:7,run:()=>wsNavigate(tab)}))];};
openSearch=async function(){closeMenus();if($('.cmdk'))return;const ov=document.createElement('div');ov.className='cmdk-wrap';ov.innerHTML=`<div class="cmdk" role="dialog" aria-label="Search everything"><div class="cmdk-in">${ICON.search}<input id="ckQ" type="search" placeholder="Payments, invoices, products, documents and research" aria-label="Search everything"><kbd>Esc</kbd></div><div id="ckList" class="cmdk-list"></div></div>`;document.body.appendChild(ov);const q=$('#ckQ');q.focus();let selected=0,shown=[],generation=0;const close=()=>ov.remove();ov.onclick=e=>{if(e.target===ov)close();};
 const run=async it=>{close();if(it.run)return it.run();if(it.kind==='public-link'&&/^https?:\/\//.test(it.url))return window.open(it.url,'_blank','noopener');if(it.kind==='research-company')return intNavigate('research',it.id);if(it.kind==='notes-text'){const dlg=$('#dlg');$('#dlgForm').innerHTML=`<h2>${esc(it.title)}</h2><pre class="ws-document">${esc(it.text)}</pre><button class="btn ghost">Close</button>`;$('#dlgForm').onsubmit=null;dlg.showModal();return;}if(it.kind==='payment')return wsOpenPayment(it.id);if(it.kind==='receipt')return wsOpenReceipt();if(it.kind==='document')return window.open('/api/receipts/source?id='+encodeURIComponent(it.source_id),'_blank','noopener');if(it.kind==='holding')return openHolding(it.id);if(it.kind==='account'){location.hash='account/'+encodeURIComponent(it.id);return;}if(it.kind==='chat'){const c=await fetch('/api/chats/get?id='+encodeURIComponent(it.id)).then(r=>r.json());CP.conv={id:c.id,messages:c.messages};openChat();return;}return wsEdit(it.kind,it.id);};
 const paint=()=>{$('#ckList',ov).innerHTML=shown.length?shown.map((it,i)=>`<button class="ck-row ${i===selected?'on':''}" data-ws-result="${i}"><span class="ck-type">${esc(it.type||it.kind)}</span><span class="ck-name">${esc(it.name||it.title)}</span><span class="ck-sub muted">${esc(it.sub||it.snippet||'')}</span></button>`).join(''):wsEmpty('No matching local records.');$$('[data-ws-result]',ov).forEach(b=>b.onclick=()=>run(shown[+b.dataset.wsResult]));$('.ck-row.on',ov)?.scrollIntoView({block:'nearest'});};
 const draw=async()=>{const gen=++generation,term=q.value.trim().toLowerCase();selected=0;shown=searchIndex().filter(it=>!term||(it.name+' '+(it.extra||'')).toLowerCase().includes(term)).slice(0,term?8:14);paint();if(!term)return;try{const r=await wsGet('search',{q:term,limit:40});if(gen!==generation||!ov.isConnected)return;shown.push(...r.items);paint();}catch{}};let timer;q.oninput=()=>{clearTimeout(timer);timer=setTimeout(draw,180);};q.onkeydown=e=>{if(e.key==='Escape')close();else if(e.key==='ArrowDown'){e.preventDefault();selected=Math.min(shown.length-1,selected+1);paint();}else if(e.key==='ArrowUp'){e.preventDefault();selected=Math.max(0,selected-1);paint();}else if(e.key==='Enter'){e.preventDefault();if(shown[selected])run(shown[selected]);}};draw();
};
wsLoadSummary();setInterval(wsLoadSummary,60000);
